"""02_type_profile.py - meme-type profiles and subset grounding per
02_TYPE_PROFILE_SPEC.md.

Run: python scripts/02_type_profile.py
Reads paths and parameters from config.py. Writes outputs/type_profile.md,
outputs/samples/type_profile.csv, outputs/samples/watermark_candidates.csv.

Join logic reused from the gate: OCR parent id = 'label' column (canonical;
validated 100% against the filename parse in the gate). Text-quality
definitions (function-word rate, all-caps, junk) are Gate C's.
"""
import os

# Must be set before spaCy is imported: thinc imports the user-site
# tensorflow, which crashes on a protobuf C-extension version mismatch
# unless protobuf falls back to its pure-Python implementation.
os.environ.setdefault("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION", "python")

import re
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import config

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

REPORT_LINES = []


def emit(line=""):
    print(line)
    REPORT_LINES.append(line)


def pct(x):
    return "{:.1f}%".format(100.0 * x)


# Gloss-cue probes, copied verbatim from scripts/01_gate.py (GATE_SPEC.md).
CUES = [
    r"\bused (?:to|as|when|in)\b",
    r"\bexpress(?:es|ing)?\b",
    r"\brefer(?:s|ring)? to\b",
    r"\breaction(?:\s+(?:image|gif|video))?\b",
    r"\bmock(?:s|ing|ery)?\b",
    r"\bparod(?:y|ies|ying)\b",
    r"\bdepict(?:s|ing)?\b",
    r"\bdescrib(?:es|ing)\b",
    r"\btypically\b",
    r"\bcaptioned\b",
    r"\bin which\b",
    r"\brepresent(?:s|ing)?\b",
]
CUE_UNION = re.compile("|".join(CUES), re.IGNORECASE)

WATERMARK_SEEDS = ("quickmeme", "memegenerator", "imgflip", "ragebuilder",
                   "9gag", "ifunny", "kapwing", "makeameme")
STRIP_CHARS = "\"'.,;:!?()[]{}<>|*~`^"


def junk_flag(text):
    """Gate C junk definition: mostly non-alphabetic, single repeated token,
    or <= 1 token after cleaning."""
    nonspace = [c for c in text if not c.isspace()]
    alpha_ratio = (sum(1 for c in nonspace if c.isalpha()) / len(nonspace)) if nonspace else 0.0
    cleaned = [re.sub(r"[^a-z0-9]", "", w) for w in text.lower().split()]
    cleaned = [w for w in cleaned if w]
    return (alpha_ratio < 0.5
            or (len(cleaned) > 1 and len(set(cleaned)) == 1)
            or len(cleaned) <= 1)


def main():
    config.OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    config.SAMPLES_DIR.mkdir(parents=True, exist_ok=True)

    emit("# Type profiles (02_TYPE_PROFILE_SPEC.md)")
    emit()
    emit("Generated by scripts/02_type_profile.py on {} with seed {}.".format(
        datetime.now().strftime("%Y-%m-%d %H:%M"), config.RANDOM_SEED))
    emit()

    entries = pd.read_csv(config.ENTRIES_CSV, dtype=str, low_memory=False)
    emit("Entries columns ({}): {}".format(len(entries.columns), list(entries.columns)))
    for col in ("Status", "Entry Type", "Type:", "About Text", "ID"):
        if col not in entries.columns:
            emit("DISCREPANCY: expected entries column '{}' absent. Stopping.".format(col))
            return
    cm = entries[(entries["Status"] == "Confirmed") & (entries["Entry Type"] == "meme")].copy()
    emit("Confirmed meme-type entries: {}".format(len(cm)))
    emit()

    ocr = pd.read_csv(config.OCR_CONFIRMED_CSV, dtype=str)
    emit("OCR columns ({}): {}".format(len(ocr.columns), list(ocr.columns)))
    for col in ("Text", "label"):
        if col not in ocr.columns:
            emit("DISCREPANCY: expected OCR column '{}' absent. Stopping.".format(col))
            return
    emit("OCR rows: {}".format(len(ocr)))
    emit()

    # Gate join + usable + intersection set, recomputed identically.
    cm_ids = set(cm["ID"].dropna())
    ocr["format_id"] = ocr["label"]
    ocr["n_tokens"] = ocr["Text"].fillna("").str.split().str.len()
    usable = ocr[ocr["format_id"].isin(cm_ids) & (ocr["n_tokens"] >= config.MIN_TOKENS)].copy()
    per_format = usable.groupby("format_id").size()

    about = cm["About Text"].fillna("")
    cm["cue_any"] = about.str.contains(CUE_UNION)
    cue_ids = set(cm.loc[cm["cue_any"], "ID"])
    intersection = {fid for fid, k in per_format.items()
                    if k >= config.MIN_INSTANCES and fid in cue_ids}
    emit("Intersection set (>= 1 cue AND >= {} usable instances): {} formats "
         "(gate reported 4,029).".format(config.MIN_INSTANCES, len(intersection)))
    emit()

    # ------------------------------------------------------------------
    emit("## 1. Normalised 'Type:' (Confirmed memes only)")
    emit()

    def norm_types(val):
        if pd.isna(val):
            return []
        return [t.strip().lower() for t in str(val).split(";") if t.strip()]

    cm["types"] = cm["Type:"].map(norm_types)
    typed = cm[cm["types"].map(len) > 0]
    type_counts = pd.Series(
        [t for ts in cm["types"] for t in ts]).value_counts()
    emit("Top 30 normalised types (multi-typed entries count once per type):")
    emit()
    emit("| Type | Entries |")
    emit("|------|---------|")
    for t, k in type_counts.head(30).items():
        emit("| {} | {} |".format(t, k))
    emit()
    multi = (typed["types"].map(len) > 1).sum()
    emit("- Distinct normalised types: {}".format(len(type_counts)))
    emit("- Multi-type rate: {} of {} typed entries ({})".format(
        multi, len(typed), pct(multi / len(typed))))
    none_all = (cm["types"].map(len) == 0)
    cm_inter = cm[cm["ID"].isin(intersection)]
    none_inter = (cm_inter["types"].map(len) == 0)
    emit("- NaN/none 'Type:' rate, all Confirmed memes: {} of {} ({})".format(
        none_all.sum(), len(cm), pct(none_all.mean())))
    emit("- NaN/none 'Type:' rate, intersection set: {} of {} ({})".format(
        none_inter.sum(), len(cm_inter), pct(none_inter.mean())))
    emit()

    # ------------------------------------------------------------------
    emit("## 2. Per-type profiles (intersection set)")
    emit()

    type_to_formats = defaultdict(set)
    for _, row in cm_inter.iterrows():
        for t in row["types"]:
            type_to_formats[t].add(row["ID"])
    top15 = sorted(type_to_formats.items(), key=lambda kv: len(kv[1]), reverse=True)[:15]

    try:
        import spacy
        nlp = spacy.load("en_core_web_sm", disable=["parser", "ner", "lemmatizer"])
    except Exception as exc:
        emit("spaCy en_core_web_sm could not be loaded: {!r}. Per-type text "
             "metrics cannot run; stopping before section 2 metrics.".format(exc))
        return
    emit("Per-type text metrics on a seeded sample of up to 300 usable texts "
         "per type (seed {}); function-word/all-caps/junk definitions are "
         "Gate C's (spaCy en stop words over alphabetic tokens; all-caps among "
         "texts with letters; junk = mostly non-alphabetic, single repeated "
         "token, or <= 1 cleaned token).".format(config.RANDOM_SEED))
    emit()

    rows = []
    for tname, fmts in top15:
        fmt_counts = per_format[per_format.index.isin(fmts)]
        pool = usable[usable["format_id"].isin(fmts)]
        sample = pool.sample(n=min(300, len(pool)), random_state=config.RANDOM_SEED)
        texts = sample["Text"].fillna("").tolist()
        docs = nlp.pipe([t.lower() for t in texts], batch_size=64)
        fw_rates, in_band = [], 0
        for doc in docs:
            alpha = [t for t in doc if t.is_alpha]
            if not alpha:
                continue
            r = sum(1 for t in alpha if t.is_stop) / len(alpha)
            fw_rates.append(r)
            in_band += 0.30 <= r <= 0.70
        with_letters = [t for t in texts if any(c.isalpha() for c in t)]
        allcaps = sum(1 for t in with_letters if t == t.upper())
        junk = sum(junk_flag(t) for t in texts)
        fw = pd.Series(fw_rates)
        rows.append({
            "type": tname,
            "n_formats": len(fmts),
            "total_usable": int(fmt_counts.sum()),
            "median_usable_per_format": float(fmt_counts.median()),
            "sample_n": len(texts),
            "median_tokens": float(sample["n_tokens"].median()),
            "fw_rate_median": round(float(fw.median()), 3),
            "fw_band_30_70": round(in_band / len(texts), 3),
            "allcaps_rate": round(allcaps / len(with_letters), 3) if with_letters else None,
            "junk_rate": round(junk / len(texts), 3),
        })

    profile = pd.DataFrame(rows)
    p = config.SAMPLES_DIR / "type_profile.csv"
    profile.to_csv(p, index=False, encoding="utf-8")
    emit("Wrote {} ({} rows).".format(p.relative_to(config.REPO_ROOT), len(profile)))
    emit()

    # ------------------------------------------------------------------
    emit("## 3. Watermark scan")
    emit()
    emit("Across {} usable OCR texts joined to Confirmed memes: candidate "
         "watermark tokens/bigrams = items in >= 200 distinct formats that "
         "contain '.com'/'.net' or a seed ({}).".format(len(usable), ", ".join(WATERMARK_SEEDS)))
    emit()

    def eligible(item):
        return (".com" in item or ".net" in item
                or any(s in item for s in WATERMARK_SEEDS))

    item_formats = defaultdict(set)
    for fid, text in zip(usable["format_id"], usable["Text"].fillna("")):
        toks = [w.strip(STRIP_CHARS) for w in text.lower().split()]
        toks = [w for w in toks if w]
        for w in toks:
            if eligible(w):
                item_formats[("token", w)].add(fid)
        for a, b in zip(toks, toks[1:]):
            bg = a + " " + b
            if eligible(bg):
                item_formats[("bigram", bg)].add(fid)

    cand = sorted(((kind, item, len(fids)) for (kind, item), fids in item_formats.items()
                   if len(fids) >= 200), key=lambda x: -x[2])
    emit("Candidates in >= 200 distinct formats: {}. Top 40:".format(len(cand)))
    emit()
    emit("| Item | Kind | Formats |")
    emit("|------|------|---------|")
    for kind, item, k in cand[:40]:
        emit("| `{}` | {} | {} |".format(item, kind, k))
    emit()
    p = config.SAMPLES_DIR / "watermark_candidates.csv"
    pd.DataFrame(cand, columns=["kind", "item", "n_formats"])[
        ["item", "kind", "n_formats"]].to_csv(p, index=False, encoding="utf-8")
    emit("Wrote draft stoplist to {} ({} rows) for human review. No stripping "
         "applied.".format(p.relative_to(config.REPO_ROOT), len(cand)))
    emit()

    # ------------------------------------------------------------------
    emit("## 4. Per-type table (sorted by intersection formats)")
    emit()
    emit("| Type | Formats | Usable inst. | Median inst./format | Sample n | "
         "Median tokens | FW median | FW 30-70% band | All-caps | Junk |")
    emit("|------|---------|--------------|---------------------|----------|"
         "---------------|-----------|----------------|----------|------|")
    for r in rows:
        emit("| {type} | {n_formats} | {total_usable} | {median_usable_per_format:.0f} | "
             "{sample_n} | {median_tokens:.0f} | {fw} | {band} | {caps} | {junk} |".format(
                 fw=pct(r["fw_rate_median"]), band=pct(r["fw_band_30_70"]),
                 caps=pct(r["allcaps_rate"]) if r["allcaps_rate"] is not None else "-",
                 junk=pct(r["junk_rate"]), **r))
    emit()
    emit("No recommendation is made here: the humans choose the subset.")
    emit()

    report = config.OUTPUTS_DIR / "type_profile.md"
    report.write_text("\n".join(REPORT_LINES), encoding="utf-8")
    print("Report written to {}".format(report))


if __name__ == "__main__":
    main()
