"""04b_block_a.py - Block A repairs and per-family controls per
04B_BLOCKA_SPEC.md.

Run: python scripts/04b_block_a.py
Imports the 04 machinery (prepare / pair_context / make_all_stats /
unstripped_sims / run_headline) - no forked pair logic. Same population,
same v2 labels, same seeds, same N_PERMUTATIONS, so every null
distribution reproduces the 04 run exactly.

Writes outputs/blocka_report.md and outputs/blocka_inference.csv.
04's pair_stats_summary.csv is left untouched for provenance.
"""
import importlib
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))
import config

A = importlib.import_module("04_analysis")

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

REPORT_LINES = []
ROWS = []


def emit(line=""):
    print(line)
    REPORT_LINES.append(line)


def log(line=""):
    # prep narration goes to stdout only; the Block A report stays focused
    print(line)


def three_ps(obs, null):
    null = np.asarray(null)
    null = null[~np.isnan(null)]
    if obs != obs or not len(null):
        return np.nan, np.nan, np.nan, np.nan, np.nan
    np1 = len(null) + 1.0
    p_up = (1.0 + (null >= obs).sum()) / np1
    p_lo = (1.0 + (null <= obs).sum()) / np1
    p_two = (1.0 + (np.abs(null) >= abs(obs)).sum()) / np1
    return p_up, p_lo, p_two, float(np.quantile(null, 0.025)), float(np.quantile(null, 0.975))


def add(contrast, measure, effect, null, n_within="", note=""):
    p_up, p_lo, p_two, q025, q975 = three_ps(effect, null)
    ROWS.append({
        "contrast": contrast, "measure": measure,
        "effect": round(float(effect), 6) if effect == effect else "",
        "p_upper": round(p_up, 6) if p_up == p_up else "",
        "p_lower": round(p_lo, 6) if p_lo == p_lo else "",
        "p_twosided": round(p_two, 6) if p_two == p_two else "",
        "null_q025": round(q025, 6) if q025 == q025 else "",
        "null_q975": round(q975, 6) if q975 == q975 else "",
        "n_within": n_within, "note": note,
    })
    return p_up, p_lo, p_two


def main():
    emit("# Block A report (04B_BLOCKA_SPEC.md)")
    emit()
    emit("Generated by scripts/04b_block_a.py on {} with seed {}; "
         "N_PERMUTATIONS={}. All machinery imported from 04_analysis; "
         "permutation streams reseeded identically, so nulls reproduce the "
         "04 run.".format(datetime.now().strftime("%Y-%m-%d %H:%M"),
                          config.RANDOM_SEED, config.N_PERMUTATIONS))
    emit()

    ns = A.prepare(log)
    if ns is None:
        return
    pc = A.pair_context(ns)
    n, L = ns.n, ns.L
    NP_ = config.N_PERMUTATIONS
    iu = pc.iu
    emit("- Population check vs 04: {} formats; pairs={}, within={}.".format(
        n, len(pc.jacc_v),
        int(A.headline_stat(ns.S_dict["fw_negjsd"], (L @ L.T) > 0, n)[1])))
    emit("- Contrast-eligible families: {}; DIRECT descriptive-only.".format(
        ns.contrast_fams))
    emit()

    # ------------------------------------------------------------------
    emit("## 1. Two-sided inference for the 04 contrasts")
    emit()
    all_stats = A.make_all_stats(ns, pc)
    obs_stats = all_stats(L, pc.L_se, pc.L_me)
    null_stats = {k: np.empty(NP_, np.float32) for k in obs_stats}
    rng = np.random.default_rng(config.RANDOM_SEED)
    for t in range(NP_):
        idx = rng.permutation(n)
        st = all_stats(L[idx], pc.L_se[idx], pc.L_me[idx])
        for k, v in st.items():
            null_stats[k][t] = v
        if (t + 1) % 2000 == 0:
            print("  main perms {}/{}".format(t + 1, NP_))

    emit("| Contrast | Measure | Effect | p_upper | p_lower | p_twosided |")
    emit("|----------|---------|--------|---------|---------|------------|")
    for key in sorted(set(k[0] for k in obs_stats)):
        for meas in ns.S_dict:
            o = obs_stats[(key, meas)]
            pu, pl, p2 = add(key, meas, o, null_stats[(key, meas)])
            emit("| {} | {} | {:.5f} | {:.4f} | {:.4f} | {:.4f} |".format(
                key, meas, o, pu, pl, p2))

    # strata, reaction-exclusion, unstripped: rebuilt with identical seeds
    subset_specs = []
    for stratum in ("exploitable", "image macro", "catchphrase"):
        sub = np.array([stratum in ts for ts in ns.type_sets])
        subset_specs.append(("stratum_" + stratum.replace(" ", "_"), sub))
    subset_specs.append((
        "excl_reaction_type",
        np.array(["reaction" not in ts for ts in ns.type_sets])))
    for tag, sub in subset_specs:
        sub_idx = np.where(sub)[0]
        Ss = {meas: S[np.ix_(sub_idx, sub_idx)] for meas, S in ns.S_dict.items()}
        r = A.run_headline(Ss, L[sub_idx], len(sub_idx), NP_,
                           np.random.default_rng(config.RANDOM_SEED), tag)
        for meas, (o, _, null) in r.items():
            pu, pl, p2 = add(tag, meas, o, null)
            emit("| {} | {} | {:.5f} | {:.4f} | {:.4f} | {:.4f} |".format(
                tag, meas, o, pu, pl, p2))

    log("  rebuilding unstripped profiles...")
    Su = A.unstripped_sims(ns)
    r = A.run_headline(Su, L, n, NP_, np.random.default_rng(config.RANDOM_SEED),
                       "unstripped")
    for meas, (o, _, null) in r.items():
        pu, pl, p2 = add("unstripped", meas, o, null)
        emit("| {} | {} | {:.5f} | {:.4f} | {:.4f} | {:.4f} |".format(
            "unstripped", meas, o, pu, pl, p2))
    emit()
    emit("Notes: p_upper is 04's one-sided p; p_lower and p_twosided are the "
         "repairs. mrqap_beta and excl_reaction_type are included beyond the "
         "spec's enumeration for completeness (both were permutation "
         "contrasts reported in 04). The CAPTION anti-coherence and the "
         "Searle reversal should be read off p_lower / p_twosided here.")
    emit()

    # ------------------------------------------------------------------
    emit("## 2. Tag diagnostic (report-only)")
    emit()
    jv = pc.jacc_v.astype(np.float64)
    dec = np.quantile(jv, np.arange(0, 1.01, 0.1))
    emit("- Pairwise tag Jaccard deciles: " +
         ", ".join("{:.0f}%: {:.4f}".format(10 * i, d) for i, d in enumerate(dec)))
    emit("- Share of pairs at exactly zero: {:.1f}% ({} of {})".format(
        100.0 * (jv == 0).mean(), int((jv == 0).sum()), len(jv)))
    emit()
    from collections import Counter as C
    tag_freq = C(t for ts in ns.tags_sets for t in ts)
    emit("Top 30 tags by format frequency:")
    emit()
    emit("| Tag | Formats |")
    emit("|-----|---------|")
    for t, k in tag_freq.most_common(30):
        emit("| {} | {} |".format(t, k))
    emit()

    order = np.argsort(-jv)[:config.TAG_DIAG_TOP_PAIRS]
    emit("Top {} highest-Jaccard pairs:".format(config.TAG_DIAG_TOP_PAIRS))
    emit()
    emit("| Jaccard | Format A | Format B | Types A | Types B | n_A | n_B | Shared tags |")
    emit("|---------|----------|----------|---------|---------|-----|-----|-------------|")
    for k in order:
        i, j = int(iu[0][k]), int(iu[1][k])
        shared = sorted(ns.tags_sets[i] & ns.tags_sets[j])
        emit("| {:.3f} | {} | {} | {} | {} | {} | {} | {} |".format(
            jv[k], ns.titles[i][:40], ns.titles[j][:40],
            ";".join(sorted(ns.type_sets[i])) or "-",
            ";".join(sorted(ns.type_sets[j])) or "-",
            ns.per_format[ns.F[i]], ns.per_format[ns.F[j]],
            "; ".join(shared[:8]) + (" (+{})".format(len(shared) - 8)
                                     if len(shared) > 8 else "")))
    emit()

    emit("Mean within-Type pair Jaccard (Types with >= 5 population formats):")
    emit()
    type_freq = C(t for ts in ns.type_sets for t in ts)
    emit("| Type | Formats | Mean within-Type Jaccard |")
    emit("|------|---------|--------------------------|")
    trs = []
    for t, k in type_freq.items():
        if k < 5:
            continue
        m = np.array([t in ts for ts in ns.type_sets])
        mask = m[iu[0]] & m[iu[1]]
        if mask.any():
            trs.append((t, k, float(jv[mask].mean())))
    for t, k, mj in sorted(trs, key=lambda x: -x[2]):
        emit("| {} | {} | {:.4f} |".format(t, k, mj))
    emit()

    from scipy.stats import spearmanr
    min_log = np.minimum(pc.log_n[iu[0]], pc.log_n[iu[1]])
    max_log = np.maximum(pc.log_n[iu[0]], pc.log_n[iu[1]])
    emit("Pair-level Spearman correlations with tag_jaccard:")
    emit()
    emit("| Variable | rho |")
    emit("|----------|-----|")
    for name, vec in [("same_type", pc.stype_v), ("min log instances", min_log),
                      ("max log instances", max_log),
                      ("fw_negjsd", pc.y_v["fw_negjsd"]),
                      ("pos_cosine", pc.y_v["pos_cosine"])]:
        rho = spearmanr(jv, np.asarray(vec, dtype=np.float64)).correlation
        emit("| {} | {:.4f} |".format(name, rho))
    emit()
    emit("(Raw bivariate associations, for comparison against the negative "
         "tag_jaccard coefficient in the 04 regression. No thresholds or "
         "filtering decisions here; interpretation in chat feeds Block B.)")
    emit()

    cand = np.where((jv >= 0.1) & (jv <= 0.3))[0]
    srng = np.random.default_rng(config.RANDOM_SEED)
    pick = srng.choice(cand, size=min(config.TAG_DIAG_MID_SAMPLE, len(cand)),
                       replace=False)
    emit("Seeded sample of {} mid-range pairs (Jaccard 0.1-0.3):".format(len(pick)))
    emit()
    for k in pick:
        i, j = int(iu[0][k]), int(iu[1][k])
        shared = sorted(ns.tags_sets[i] & ns.tags_sets[j])
        emit("- {:.3f} | {} <-> {} | shared: {}".format(
            jv[k], ns.titles[i][:45], ns.titles[j][:45], "; ".join(shared[:6])))
    emit()

    # ------------------------------------------------------------------
    emit("## 3. Per-family controls (all >= {}-clause families)".format(
        config.FAMILY_CONTRAST_MIN_CLAUSES))
    emit()
    fam_idx = [(j, fam) for j, fam in enumerate(A.FAMILIES)
               if fam in ns.contrast_fams]
    z0 = pc.zerotag
    i_idx, j_idx = iu[0], iu[1]

    def fam_vectors(a_bool):
        ai, aj = a_bool[i_idx], a_bool[j_idx]
        return ai & aj, ai ^ aj

    obs_fam = {}
    for j, fam in fam_idx:
        a = L[:, j] > 0
        w, x = fam_vectors(a)
        nz_w = int((z0 & w).sum())
        for meas in ns.S_dict:
            sv = pc.y_v[meas]
            zt_eff = (sv[z0 & w].mean() - sv[z0 & x].mean()
                      if (z0 & w).any() and (z0 & x).any() else np.nan)
            beta = pc.fwl_beta(w.astype(np.float64), meas)
            obs_fam[(fam, meas)] = (zt_eff, beta, nz_w)

    null_zt = {k: np.empty(NP_, np.float32) for k in obs_fam}
    null_b = {k: np.empty(NP_, np.float32) for k in obs_fam}
    frng = np.random.default_rng(config.RANDOM_SEED)
    for t in range(NP_):
        idx = frng.permutation(n)
        Lp = L[idx]
        for j, fam in fam_idx:
            a = Lp[:, j] > 0
            w, x = fam_vectors(a)
            wf = w.astype(np.float64)
            for meas in ns.S_dict:
                sv = pc.y_v[meas]
                zm, zb = z0 & w, z0 & x
                null_zt[(fam, meas)][t] = (sv[zm].mean() - sv[zb].mean()
                                           if zm.any() and zb.any() else np.nan)
                null_b[(fam, meas)][t] = pc.fwl_beta(wf, meas)
        if (t + 1) % 2000 == 0:
            print("  family-control perms {}/{}".format(t + 1, NP_))

    emit("| Family | Measure | Uncontrolled (04) | Zerotag effect | zt p_up/p_lo/p_2 | zt n_within | MRQAP beta | b p_up/p_lo/p_2 |")
    emit("|--------|---------|-------------------|----------------|------------------|-------------|------------|-----------------|")
    for j, fam in fam_idx:
        for meas in ns.S_dict:
            zt_eff, beta, nz_w = obs_fam[(fam, meas)]
            unc = obs_stats[("fam_" + fam, meas)]
            thin = nz_w < 100
            note = "zerotag descriptive (<100 within-pairs)" if thin else ""
            pu, pl, p2 = add("famZT_" + fam, meas, zt_eff,
                             null_zt[(fam, meas)], n_within=nz_w, note=note)
            bu, bl, b2 = add("famMRQAP_" + fam, meas, beta, null_b[(fam, meas)])
            emit("| {} | {} | {:.5f} | {:.5f}{} | {:.4f}/{:.4f}/{:.4f} | {} | {:.5f} | {:.4f}/{:.4f}/{:.4f} |".format(
                fam, meas, unc, zt_eff, " (descr.)" if thin else "",
                pu, pl, p2, nz_w, beta, bu, bl, b2))
    emit()
    flagged = sorted({fam for (j, fam) in fam_idx
                      if obs_fam[(fam, list(ns.S_dict)[0])][2] < 100})
    if flagged:
        emit("Flagged (zerotag within-pairs < 100, treat zerotag result as "
             "descriptive): {}.".format(", ".join(flagged)))
    else:
        emit("No family fell below 100 zerotag within-pairs.")
    emit()
    emit("Interpretation happens in chat.")

    pd.DataFrame(ROWS).to_csv(config.OUTPUTS_DIR / "blocka_inference.csv",
                              index=False, encoding="utf-8")
    emit()
    emit("Wrote outputs/blocka_inference.csv ({} rows).".format(len(ROWS)))
    (config.OUTPUTS_DIR / "blocka_report.md").write_text(
        "\n".join(REPORT_LINES), encoding="utf-8")
    print("Report written to outputs/blocka_report.md")


if __name__ == "__main__":
    main()
