"""04c_block_b.py - Block B content layer per 04C_BLOCKB_SPEC.md.

Run: python scripts/04c_block_b.py
Imports the shared 04 functions; same population, v2 labels, permutation
scheme, N_PERMUTATIONS, seeded throughout. Both tails and two-sided p
reported for every contrast from the start.

Ratified choices: (a) fresh BAAI/bge-large-en-v1.5 embeddings, symmetric
mode (no query prefix), L2-normalised, on the 04-prepared instance texts;
the SemioMeme fine-tuned retrieval embeddings are NOT used (circularity);
(b) format content profile = instance-embedding centroid, pair similarity =
centroid cosine; (c) transparent separability = decile stratification on
content similarity (zerotag retired: Block A showed it removes only 6% of
pairs and measures category/platform, not topic); (d) complement test
confirmatory for EXPRESS only, EVALUATE descriptive (poke-fun corrupts its
comp_head).

Writes outputs/blockb_report.md, outputs/blockb_grid.csv, and three figures.
"""
import importlib
import sys
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))
import config

A = importlib.import_module("04_analysis")

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

REPORT_LINES = []
GRID_ROWS = []


def emit(line=""):
    print(line)
    REPORT_LINES.append(line)


def log(line=""):
    print(line)


def three_ps(obs, null):
    null = np.asarray(null, dtype=np.float64)
    null = null[~np.isnan(null)]
    if obs != obs or not len(null):
        return np.nan, np.nan, np.nan
    np1 = len(null) + 1.0
    return ((1.0 + (null >= obs).sum()) / np1,
            (1.0 + (null <= obs).sum()) / np1,
            (1.0 + (np.abs(null) >= abs(obs)).sum()) / np1)


def grid_row(family, layer, effect, null, kind, note=""):
    pu, pl, p2 = three_ps(effect, null)
    GRID_ROWS.append({
        "family": family, "layer": layer, "kind": kind,
        "effect": round(float(effect), 6) if effect == effect else "",
        "p_upper": round(pu, 6) if pu == pu else "",
        "p_lower": round(pl, 6) if pl == pl else "",
        "p_twosided": round(p2, 6) if p2 == p2 else "",
        "note": note})
    return pu, pl, p2


def main():
    figs = config.OUTPUTS_DIR / "figures"
    figs.mkdir(parents=True, exist_ok=True)

    emit("# Block B report: the content layer (04C_BLOCKB_SPEC.md)")
    emit()
    emit("Generated by scripts/04c_block_b.py on {} with seed {}; "
         "N_PERMUTATIONS={}.".format(datetime.now().strftime("%Y-%m-%d %H:%M"),
                                     config.RANDOM_SEED, config.N_PERMUTATIONS))
    emit()
    emit("## 0. Registered predictions (fixed before running)")
    emit()
    emit("- Confirmatory, one-sided: EXPRESS one-vs-rest content effect > 0; "
         "EVALUATE one-vs-rest content effect > 0; EXPRESS complement-content "
         "Spearman > 0.")
    emit("- Exploratory, two-sided: omnibus content effect; LABEL, RESPOND, "
         "STRUCTURAL, CAPTION content effects. (Registered note: LABEL "
         "plausibly binds form without binding content - the labelling "
         "construction is fixed while the labelled subject varies; a "
         "form-without-content cell would be a finding, not a failure.)")
    emit()

    ns = A.prepare(log)
    if ns is None:
        return
    pc = A.pair_context(ns)
    n, L = ns.n, ns.L
    NP_ = config.N_PERMUTATIONS
    iu = pc.iu
    rngs = lambda: np.random.default_rng(config.RANDOM_SEED)

    emit("## Population resolution: 1,622 vs 1,623")
    emit()
    emit("The pair-classification population is 1,623 formats (>= 1 "
         "usage-family clause, >= {} usable instances, >= 1 non-OTHER v2 "
         "label). One format - {} - loses its entire function-word profile "
         "to watermark stripping + the re-applied MIN_TOKENS filter, so all "
         "pair analyses run on the canonical n = {}. 04's section-0 count "
         "(1,623) is the pre-profile population; every pair statistic in 04, "
         "Block A and this block uses {}.".format(
             config.MIN_INSTANCES,
             ", ".join(ns.dropped_formats) or "(see prepare log)",
             n, n))
    emit()

    # ------------------------------------------------------------------
    emit("## 1. Content layer")
    emit()
    import torch
    import sentence_transformers
    from sentence_transformers import SentenceTransformer
    model = SentenceTransformer(config.CONTENT_MODEL, device="cuda")
    import glob, os
    snaps = glob.glob(os.path.expanduser(
        "~/.cache/huggingface/hub/models--{}/snapshots/*".format(
            config.CONTENT_MODEL.replace("/", "--"))))
    revision = os.path.basename(snaps[0]) if snaps else "unknown"
    emit("- Model: {} (revision {}), symmetric similarity mode (no query "
         "instruction prefix), embeddings L2-normalised. sentence-transformers "
         "{}, torch {}, GPU: {}.".format(
             config.CONTENT_MODEL, revision, sentence_transformers.__version__,
             torch.__version__, torch.cuda.get_device_name(0)))

    Fset = set(ns.F)
    inst = ns.kept[ns.kept["format_id"].isin(Fset)]
    texts = inst["text_stripped"].tolist()
    fmt_rows = np.array([ns.fid_index[f] for f in inst["format_id"]])
    emit("- Encoding {} prepared instance texts (stripped, filtered, capped "
         "seeded sample) across {} formats.".format(len(texts), n))
    emb = model.encode(texts, batch_size=256, convert_to_numpy=True,
                       normalize_embeddings=True, show_progress_bar=False)
    emb = emb.astype(np.float32)

    C = np.zeros((n, emb.shape[1]), np.float32)
    np.add.at(C, fmt_rows, emb)
    counts = np.bincount(fmt_rows, minlength=n).astype(np.float32)
    C = C / counts[:, None]
    cap_counts = inst.groupby("format_id").size()
    match = all(int(counts[ns.fid_index[f]]) == int(cap_counts[f]) for f in ns.F)
    emit("- Centroid instance counts equal the 04 capped (post-strip) counts: "
         "{}. Total instances {}, min/median/max per format {}/{}/{}.".format(
             "yes" if match else "NO - MISMATCH",
             int(counts.sum()), int(counts.min()),
             int(np.median(counts)), int(counts.max())))
    S_content = A.cosine_matrix(C)
    content_v = S_content[iu].astype(np.float64)
    emit()

    # one combined permutation loop: omnibus content, per-family content
    # one-vs-rest, per-family MRQAP (content control), per-family pooled
    # decile estimate
    fam_list = [(j, fam) for j, fam in enumerate(A.FAMILIES)
                if fam in ns.contrast_fams]
    Z2 = np.column_stack([np.ones(len(content_v)), content_v,
                          pc.stype_v.astype(np.float64),
                          pc.lsum_v.astype(np.float64)])
    Z2inv = np.linalg.pinv(Z2)
    ey2 = {meas: pc.y_v[meas] - Z2 @ (Z2inv @ pc.y_v[meas])
           for meas in ns.S_dict}

    def fwl2(m_v, meas):
        ex = m_v - Z2 @ (Z2inv @ m_v)
        d = float(ex @ ex)
        return float(ex @ ey2[meas]) / d if d else np.nan

    bins = pd.qcut(content_v, config.CONTENT_DECILES, labels=False,
                   duplicates="drop").astype(np.int64)
    n_bins = int(bins.max()) + 1
    i_idx, j_idx = iu

    def decile_stats(w, x, s):
        bw, bx = bins[w], bins[x]
        sw = np.bincount(bw, weights=s[w], minlength=n_bins)
        cw = np.bincount(bw, minlength=n_bins)
        sx = np.bincount(bx, weights=s[x], minlength=n_bins)
        cx = np.bincount(bx, minlength=n_bins)
        ok = (cw > 0) & (cx > 0)
        eff = np.where(ok, sw / np.maximum(cw, 1) - sx / np.maximum(cx, 1), np.nan)
        pooled = (np.nansum(eff[ok] * cw[ok]) / cw[ok].sum()) if ok.any() else np.nan
        return eff, cw, pooled

    def block_stats(Lc):
        out = {}
        M = (Lc @ Lc.T) > 0
        out[("omnibus", "content")] = A.headline_stat(S_content, M, n)[0]
        for j, fam in fam_list:
            a = Lc[:, j]
            mw, mb, _, _ = A.pair_means(S_content, a)
            out[(fam, "content")] = mw - mb
            ab = a > 0
            w = ab[i_idx] & ab[j_idx]
            x = ab[i_idx] ^ ab[j_idx]
            wf = w.astype(np.float64)
            for meas in ns.S_dict:
                out[(fam, "mrqap_" + meas)] = fwl2(wf, meas)
                out[(fam, "decile_" + meas)] = decile_stats(w, x, pc.y_v[meas])[2]
        return out

    obs = block_stats(L)
    nulls = {k: np.empty(NP_, np.float32) for k in obs}
    rng = rngs()
    for t in range(NP_):
        st = block_stats(L[rng.permutation(n)])
        for k, v in st.items():
            nulls[k][t] = v
        if (t + 1) % 1000 == 0:
            print("  block perms {}/{}".format(t + 1, NP_))

    emit("### Content-layer contrasts (one-vs-rest on centroid cosine)")
    emit()
    emit("| Contrast | Effect | p_upper | p_lower | p_twosided | Status |")
    emit("|----------|--------|---------|---------|------------|--------|")
    o = obs[("omnibus", "content")]
    pu, pl, p2 = grid_row("(omnibus)", "content_cosine", o,
                          nulls[("omnibus", "content")], "one_vs_rest",
                          "exploratory two-sided")
    emit("| omnibus | {:.5f} | {:.4f} | {:.4f} | {:.4f} | exploratory |".format(
        o, pu, pl, p2))
    CONFIRMATORY = {"EXPRESS", "EVALUATE"}
    for j, fam in fam_list:
        o = obs[(fam, "content")]
        status = ("confirmatory one-sided (p_upper)" if fam in CONFIRMATORY
                  else "exploratory two-sided")
        pu, pl, p2 = grid_row(fam, "content_cosine", o, nulls[(fam, "content")],
                              "one_vs_rest", status)
        emit("| {} | {:.5f} | {:.4f} | {:.4f} | {:.4f} | {} |".format(
            fam, o, pu, pl, p2, status.split(" (")[0]))
    # DIRECT descriptive
    jd = A.FAMILIES.index("DIRECT")
    ad = L[:, jd]
    if ad.sum() >= 2:
        mw, mb, nw, nb = A.pair_means(S_content, ad)
        emit("| DIRECT (descriptive) | {:.5f} | - | - | - | within {:.5f} vs "
             "between {:.5f} (n={}/{}) |".format(mw - mb, mw, mb, nw, nb))
    emit()

    # family x layer grid (form numbers from the committed Block A inference)
    blocka = pd.read_csv(config.OUTPUTS_DIR / "blocka_inference.csv")
    emit("### The family x layer grid (the paper's central table)")
    emit()
    emit("| Family | FW effect (p2) | POS effect (p2) | Content effect (p2) |")
    emit("|--------|----------------|-----------------|---------------------|")
    for j, fam in fam_list:
        cells = []
        for meas in ("fw_negjsd", "pos_cosine"):
            r = blocka[(blocka["contrast"] == "fam_" + fam) &
                       (blocka["measure"] == meas)].iloc[0]
            cells.append("{:+.4f} ({:.4f})".format(r["effect"], r["p_twosided"]))
            GRID_ROWS.append({
                "family": fam, "layer": meas, "kind": "one_vs_rest",
                "effect": r["effect"], "p_upper": r["p_upper"],
                "p_lower": r["p_lower"], "p_twosided": r["p_twosided"],
                "note": "from blocka_inference.csv"})
        o = obs[(fam, "content")]
        _, _, p2 = three_ps(o, nulls[(fam, "content")])
        cells.append("{:+.4f} ({:.4f})".format(o, p2))
        emit("| {} | {} | {} | {} |".format(fam, *cells))
    emit()

    # ------------------------------------------------------------------
    emit("## 2. Separability: form binding with content held fixed")
    emit()
    emit("### MRQAP: form similarity ~ within_family + content_similarity + "
         "same_type + log sizes")
    emit()
    emit("| Family | Measure | within_family beta | p_upper | p_lower | p_twosided |")
    emit("|--------|---------|--------------------|---------|---------|------------|")
    for j, fam in fam_list:
        for meas in ns.S_dict:
            o = obs[(fam, "mrqap_" + meas)]
            pu, pl, p2 = grid_row(fam, meas, o, nulls[(fam, "mrqap_" + meas)],
                                  "mrqap_content_controlled")
            emit("| {} | {} | {:.5f} | {:.4f} | {:.4f} | {:.4f} |".format(
                fam, meas, o, pu, pl, p2))
    emit()

    emit("### Decile stratification on content similarity ({} bins)".format(n_bins))
    emit()
    dec_table = {}
    emit("| Family | Measure | Pooled within-decile effect | p_upper | p_lower | p_twosided | Thin cells (<100 within) |")
    emit("|--------|---------|-----------------------------|---------|---------|------------|--------------------------|")
    for j, fam in fam_list:
        ab = L[:, j] > 0
        w = ab[i_idx] & ab[j_idx]
        x = ab[i_idx] ^ ab[j_idx]
        for meas in ns.S_dict:
            eff_d, cw, pooled = decile_stats(w, x, pc.y_v[meas])
            dec_table[(fam, meas)] = (eff_d, cw)
            thin = [d for d in range(n_bins) if cw[d] < 100]
            pu, pl, p2 = grid_row(fam, meas, pooled,
                                  nulls[(fam, "decile_" + meas)],
                                  "pooled_decile",
                                  "thin deciles: {}".format(thin) if thin else "")
            emit("| {} | {} | {:.5f} | {:.4f} | {:.4f} | {:.4f} | {} |".format(
                fam, meas, pooled, pu, pl, p2, thin if thin else "-"))
    emit()
    emit("Pooling weights = within-pair count per decile (deciles are "
         "equal-sized overall, so weighting matters only through within-pair "
         "placement). Per-decile effects, all families (cells with < 100 "
         "within-pairs marked *):")
    emit()
    emit("| Family | Measure | " + " | ".join(
        "D{}".format(d + 1) for d in range(n_bins)) + " |")
    emit("|--------|---------|" + "----|" * n_bins)
    for j, fam in fam_list:
        for meas in ns.S_dict:
            eff_d, cw = dec_table[(fam, meas)]
            cells = ["{:+.4f}{}".format(eff_d[d], "*" if cw[d] < 100 else "")
                     if eff_d[d] == eff_d[d] else "-"
                     for d in range(n_bins)]
            emit("| {} | {} | {} |".format(fam, meas, " | ".join(cells)))
    emit()
    from scipy.stats import spearmanr
    emit("Raw form-content relationship over all pairs: Spearman content vs "
         "fw_negjsd = {:.4f}; vs pos_cosine = {:.4f}.".format(
             spearmanr(content_v, pc.y_v["fw_negjsd"]).correlation,
             spearmanr(content_v, pc.y_v["pos_cosine"]).correlation))
    emit()

    # ------------------------------------------------------------------
    emit("## 3. Complement test (EXPRESS confirmatory; EVALUATE descriptive)")
    emit()
    cl = ns.clauses
    pop_express = cl[(cl["label_v2"] == "EXPRESS") & cl["entry_id"].isin(Fset)]
    stop = set(config.COMPLEMENT_HEAD_STOPLIST)

    def usable_heads(df):
        heads = defaultdict(set)
        for fid, h in zip(df["entry_id"], df["comp_head"]):
            if isinstance(h, str) and h.strip() and h.strip().lower() not in stop:
                heads[fid].add(h.strip().lower())
        return heads

    ex_heads = usable_heads(pop_express)
    jx = A.FAMILIES.index("EXPRESS")
    ex_carriers = [f for f in ns.F if L[ns.fid_index[f], jx] > 0]
    with_heads = [f for f in ex_carriers if f in ex_heads]
    emit("- comp_head values are spaCy lemmas from extraction (03); "
         "lowercased here. Light-head stoplist (config): {}.".format(
             sorted(stop)))
    emit("- Coverage: {} of {} population EXPRESS formats carry >= 1 usable "
         "head.".format(len(with_heads), len(ex_carriers)))

    head_vocab = sorted({h for f in with_heads for h in ex_heads[f]})
    H = model.encode(head_vocab, batch_size=256, convert_to_numpy=True,
                     normalize_embeddings=True).astype(np.float32)
    hidx = {h: i for i, h in enumerate(head_vocab)}
    G = H @ H.T
    k = len(with_heads)
    sets = [np.array([hidx[h] for h in sorted(ex_heads[f])]) for f in with_heads]
    setmax = np.zeros((k, k), np.float32)
    for p in range(k):
        for q in range(p + 1, k):
            m = float(G[np.ix_(sets[p], sets[q])].max())
            setmax[p, q] = setmax[q, p] = m

    rows_g = np.array([ns.fid_index[f] for f in with_heads])
    sub = np.ix_(rows_g, rows_g)
    iu_k = np.triu_indices(k, k=1)
    comp_obs = setmax[iu_k]
    cont_pairs = S_content[sub][iu_k].astype(np.float64)
    fw_pairs = ns.S_dict["fw_negjsd"][sub][iu_k].astype(np.float64)
    pos_pairs = ns.S_dict["pos_cosine"][sub][iu_k].astype(np.float64)
    emit("- EXPRESS-EXPRESS pairs with usable heads: {} (head vocab {}).".format(
        len(comp_obs), len(head_vocab)))
    emit()

    def head_perm_null(stat_fn, n_perm):
        out = np.empty(n_perm, np.float64)
        prng = rngs()
        for t in range(n_perm):
            pm = prng.permutation(k)
            out[t] = stat_fn(setmax[np.ix_(pm, pm)][iu_k])
        return out

    rho_obs = spearmanr(comp_obs, cont_pairs).correlation
    null_rho = head_perm_null(
        lambda cv: spearmanr(cv, cont_pairs).correlation, NP_)
    pu, pl, p2 = grid_row("EXPRESS", "complement_vs_content", rho_obs,
                          null_rho, "spearman", "confirmatory one-sided")
    emit("- CONFIRMATORY: Spearman(complement max-cosine, content cosine) = "
         "{:.4f}; one-sided p = {:.4f} (two-sided {:.4f}).".format(
             rho_obs, pu, p2))

    qual = [h for h in head_vocab
            if sum(1 for f in with_heads if h in ex_heads[f])
            >= config.COMPLEMENT_MIN_FORMATS_PER_HEAD]
    qual_counts = {h: sum(1 for f in with_heads if h in ex_heads[f]) for h in qual}
    qual_sets = [frozenset(h for h in ex_heads[f] if h in qual) for f in with_heads]
    share_mat = np.zeros((k, k), bool)
    for p in range(k):
        for q in range(p + 1, k):
            share_mat[p, q] = share_mat[q, p] = bool(qual_sets[p] & qual_sets[q])
    same_v = share_mat[iu_k]
    if same_v.any() and (~same_v).any():
        d_obs = cont_pairs[same_v].mean() - cont_pairs[~same_v].mean()
        prng = rngs()
        null_d = np.empty(NP_, np.float64)
        for t in range(NP_):
            pm = prng.permutation(k)
            sv = share_mat[np.ix_(pm, pm)][iu_k]
            null_d[t] = (cont_pairs[sv].mean() - cont_pairs[~sv].mean()
                         if sv.any() and (~sv).any() else np.nan)
        pu, pl, p2 = grid_row("EXPRESS", "samehead_vs_content", d_obs, null_d,
                              "discrete_contrast")
        emit("- Discrete companion: same-head vs different-head content "
             "contrast = {:.5f}; p_upper {:.4f}, two-sided {:.4f}. "
             "Qualifying heads (>= {} formats): {}.".format(
                 d_obs, pu, p2, config.COMPLEMENT_MIN_FORMATS_PER_HEAD,
                 ", ".join("{} ({})".format(h, qual_counts[h])
                           for h in sorted(qual, key=lambda x: -qual_counts[x]))))
    emit()
    for name, fp in (("fw_negjsd", fw_pairs), ("pos_cosine", pos_pairs)):
        r = spearmanr(comp_obs, fp).correlation
        nr = head_perm_null(lambda cv, fp=fp: spearmanr(cv, fp).correlation, NP_)
        pu, pl, p2 = grid_row("EXPRESS", "complement_vs_" + name, r, nr,
                              "spearman", "secondary exploratory")
        emit("- Secondary (exploratory, two-sided): Spearman(complement, {}) "
             "= {:.4f}, two-sided p = {:.4f}.".format(name, r, p2))
    emit()

    ev = cl[(cl["label_v2"] == "EVALUATE") & cl["entry_id"].isin(Fset)]
    ev_heads_all = Counter(h.strip().lower() for h in ev["comp_head"]
                           if isinstance(h, str) and h.strip())
    emit("EVALUATE (descriptive only): top lemmatised heads: {}. NOTE: the "
         "poke-fun construction corrupts comp_head ('fun' is the recorded "
         "head for make_fun_of/poke_fun_at clauses), so EVALUATE complements "
         "are not confirmatory; the continuous correlation is reported "
         "without confirmatory status in blockb_grid.csv.".format(
             ", ".join("{} ({})".format(h, c)
                       for h, c in ev_heads_all.most_common(15))))
    ev_heads = usable_heads(ev[~ev["predicate"].isin(["make_fun_of", "poke_fun_at"])])
    jv_ = A.FAMILIES.index("EVALUATE")
    ev_with = [f for f in ns.F if L[ns.fid_index[f], jv_] > 0 and f in ev_heads]
    if len(ev_with) >= 10:
        hv = sorted({h for f in ev_with for h in ev_heads[f]})
        Hv = model.encode(hv, batch_size=256, convert_to_numpy=True,
                          normalize_embeddings=True).astype(np.float32)
        hvidx = {h: i for i, h in enumerate(hv)}
        Gv = Hv @ Hv.T
        kv = len(ev_with)
        vsets = [np.array([hvidx[h] for h in sorted(ev_heads[f])]) for f in ev_with]
        vmax = np.zeros((kv, kv), np.float32)
        for p in range(kv):
            for q in range(p + 1, kv):
                m = float(Gv[np.ix_(vsets[p], vsets[q])].max())
                vmax[p, q] = vmax[q, p] = m
        rv = np.array([ns.fid_index[f] for f in ev_with])
        iu_v = np.triu_indices(kv, k=1)
        cv_pairs = S_content[np.ix_(rv, rv)][iu_v].astype(np.float64)
        r_ev = spearmanr(vmax[iu_v], cv_pairs).correlation
        grid_row("EVALUATE", "complement_vs_content", r_ev, [], "spearman",
                 "descriptive only; poke-fun heads excluded")
        emit("EVALUATE continuous correlation (descriptive, poke-fun clauses "
             "excluded; {} formats): Spearman = {:.4f}.".format(kv, r_ev))
    emit()

    # ------------------------------------------------------------------
    # figures
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fams = [fam for _, fam in fam_list]
    layers = ["fw_negjsd", "pos_cosine", "content_cosine"]
    Gm = np.zeros((len(fams), 3))
    Pm = np.zeros((len(fams), 3))
    gdf = pd.DataFrame(GRID_ROWS)
    for r_i, fam in enumerate(fams):
        for c_i, lay in enumerate(layers):
            row = gdf[(gdf["family"] == fam) & (gdf["layer"] == lay) &
                      (gdf["kind"] == "one_vs_rest")].iloc[0]
            Gm[r_i, c_i] = float(row["effect"])
            Pm[r_i, c_i] = float(row["p_twosided"])
    fig, ax = plt.subplots(figsize=(7, 4.5))
    vmax_abs = np.abs(Gm).max()
    im = ax.imshow(Gm, cmap="RdBu_r", vmin=-vmax_abs, vmax=vmax_abs)
    ax.set_xticks(range(3))
    ax.set_xticklabels(["FW (-JSD)", "POS trigram", "Content (bge)"])
    ax.set_yticks(range(len(fams)))
    ax.set_yticklabels(fams)
    for r_i in range(len(fams)):
        for c_i in range(3):
            ax.text(c_i, r_i, "{:+.3f}\np2={:.3f}".format(Gm[r_i, c_i], Pm[r_i, c_i]),
                    ha="center", va="center", fontsize=7)
    ax.set_title("One-vs-rest effects: family x layer")
    fig.colorbar(im, shrink=0.8)
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(figs / ("blockb_grid_heatmap." + ext), dpi=200)
    plt.close(fig)

    fig, axes = plt.subplots(1, 2, figsize=(10, 4), sharex=True)
    for ax, meas in zip(axes, ["fw_negjsd", "pos_cosine"]):
        for fam, colr in (("LABEL", "tab:blue"), ("EVALUATE", "tab:orange")):
            eff_d, cw = dec_table[(fam, meas)]
            ax.plot(range(1, n_bins + 1), eff_d, "o-", color=colr, label=fam)
        ax.axhline(0, color="black", lw=0.5)
        ax.set_xlabel("content-similarity decile (1 = least similar)")
        ax.set_ylabel("one-vs-rest form effect")
        ax.set_title(meas)
        ax.legend(fontsize=8)
    fig.suptitle("Form effects within content-similarity deciles")
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(figs / ("blockb_decile_effects." + ext), dpi=200)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(6, 4.5))
    ax.scatter(comp_obs, cont_pairs, s=3, alpha=0.05, color="tab:purple")
    ax.set_xlabel("complement similarity (max head cosine)")
    ax.set_ylabel("content similarity (centroid cosine)")
    ax.set_title("EXPRESS within-pairs: complement vs content "
                 "(rho={:.3f})".format(rho_obs))
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(figs / ("blockb_express_complement." + ext), dpi=200)
    plt.close(fig)
    emit("Figures: blockb_grid_heatmap, blockb_decile_effects, "
         "blockb_express_complement (PDF+PNG).")
    emit()
    emit("Decision point B - the framing decision - happens in chat on these "
         "results.")

    pd.DataFrame(GRID_ROWS).to_csv(config.OUTPUTS_DIR / "blockb_grid.csv",
                                   index=False, encoding="utf-8")
    emit()
    emit("Wrote outputs/blockb_grid.csv ({} rows).".format(len(GRID_ROWS)))
    (config.OUTPUTS_DIR / "blockb_report.md").write_text(
        "\n".join(REPORT_LINES), encoding="utf-8")
    print("Report written to outputs/blockb_report.md")


if __name__ == "__main__":
    main()
