"""04d_block_c.py - Block C visual layer and gallery-noise check per
04D_BLOCKC_SPEC.md.

Run: python scripts/04d_block_c.py
Imports the shared 04 functions; canonical population (1,622), v2 labels,
N_PERMUTATIONS = 10,000, seeded, both tails + two-sided p throughout.
Scope per decision point B: visual one-vs-rest, coherence-restriction
robustness, one completing regression. Nothing else.

Choice (a) verification (recorded in the report): the stored vision chunks
are BASE google/siglip-base-patch16-384 pooler outputs - the generator
script (SemioMeme 02_Retrieval/01_extract_image_embeddings.py) loads the
plain pretrained model with no checkpoint, dim is 768 (siglip-base hidden),
and the vectors are NOT unit-norm (norms ~12), whereas the fine-tuned
ProjectionHead F.normalize()s its outputs by construction. The script
re-checks the norm signature over a sample at runtime and stops if any
unit-norm block is found.
"""
import importlib
import json
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))
import config

A = importlib.import_module("04_analysis")

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

REPORT_LINES = []
GRID_ROWS = []


def emit(line=""):
    print(line)
    REPORT_LINES.append(line)


def log(line=""):
    print(line)


def three_ps(obs, null):
    null = np.asarray(null, dtype=np.float64)
    null = null[~np.isnan(null)]
    if obs != obs or not len(null):
        return np.nan, np.nan, np.nan
    np1 = len(null) + 1.0
    return ((1.0 + (null >= obs).sum()) / np1,
            (1.0 + (null <= obs).sum()) / np1,
            (1.0 + (np.abs(null) >= abs(obs)).sum()) / np1)


def grid_row(family, layer, effect, null, kind, note=""):
    pu, pl, p2 = three_ps(effect, null)
    GRID_ROWS.append({
        "family": family, "layer": layer, "kind": kind,
        "effect": round(float(effect), 6) if effect == effect else "",
        "p_upper": round(pu, 6) if pu == pu else "",
        "p_lower": round(pl, 6) if pl == pl else "",
        "p_twosided": round(p2, 6) if p2 == p2 else "",
        "note": note})
    return pu, pl, p2


def main():
    figs = config.OUTPUTS_DIR / "figures"
    figs.mkdir(parents=True, exist_ok=True)

    emit("# Block C report: the visual layer and the gallery-noise check "
         "(04D_BLOCKC_SPEC.md)")
    emit()
    emit("Generated by scripts/04d_block_c.py on {} with seed {}; "
         "N_PERMUTATIONS={}.".format(datetime.now().strftime("%Y-%m-%d %H:%M"),
                                     config.RANDOM_SEED, config.N_PERMUTATIONS))
    emit()
    emit("## 0. Registered predictions (fixed before running)")
    emit()
    emit("- Confirmatory, one-sided: EXPRESS one-vs-rest visual effect > 0 "
         "(emotion-face imagery); RESPOND one-vs-rest visual effect > 0 "
         "(reaction-image iconography).")
    emit("- Exploratory, two-sided: omnibus visual; EVALUATE, LABEL, "
         "STRUCTURAL, CAPTION visual effects. The robustness rerun is a "
         "check, not a hypothesis: no registered direction.")
    emit()

    ns = A.prepare(log)
    if ns is None:
        return
    pc = A.pair_context(ns)
    n, L = ns.n, ns.L
    NP_ = config.N_PERMUTATIONS
    iu = pc.iu
    i_idx, j_idx = iu
    Fset = set(ns.F)
    fam_list = [(j, fam) for j, fam in enumerate(A.FAMILIES)
                if fam in ns.contrast_fams]

    # ------------------------------------------------------------------
    emit("## Choice (a) verification: base, not fine-tuned")
    emit()
    emit("- Generator (SemioMeme 02_Retrieval/01_extract_image_embeddings.py) "
         "loads plain AutoModel.from_pretrained('google/siglip-base-"
         "patch16-384') and stores vision_model(...).pooler_output; no "
         "fine-tuned checkpoint is loaded anywhere in that script.")
    emit("- Structural signature: the fine-tuned ProjectionHead "
         "(config/models.py, 'exactly as in finetune_siglip.py') ends in "
         "F.normalize, so fine-tuned vectors are unit-norm by construction; "
         "the stored chunks are 768-d (siglip-base hidden size) and "
         "non-unit-norm.")
    emit("- Direct re-embedding comparison was not possible in this "
         "environment (local transformers 4.36 predates SigLIP support); "
         "the norm signature below is the runtime numeric check.")

    meta_files = sorted(config.VISION_METADATA_DIR.glob("metadata_chunk_*.json"))
    emb_files = sorted(config.VISION_EMBEDDINGS_DIR.glob("embeddings_chunk_*.npy"))
    fname_to_loc = {}
    rng_check = np.random.default_rng(config.RANDOM_SEED)
    norm_stats = []
    for ci, (mf, ef) in enumerate(zip(meta_files, emb_files)):
        m = json.loads(Path(mf).read_text())
        arr = np.load(ef, mmap_mode="r")
        assert len(m["valid_images"]) == arr.shape[0], \
            "row/metadata mismatch in chunk {}".format(ci)
        for ri, im in enumerate(m["valid_images"]):
            fname_to_loc[im["filename"]] = (ci, ri)
        sample = rng_check.choice(arr.shape[0], size=min(200, arr.shape[0]),
                                  replace=False)
        norms = np.linalg.norm(np.asarray(arr[np.sort(sample)]), axis=1)
        norm_stats.append((float(norms.min()), float(norms.max())))
    all_min = min(a for a, _ in norm_stats)
    all_max = max(b for _, b in norm_stats)
    emit("- Norm check over 200 sampled rows per chunk ({} chunks): min "
         "{:.3f}, max {:.3f}. Unit-norm would indicate fine-tuned output.".format(
             len(norm_stats), all_min, all_max))
    if all_max < 1.5:
        emit("- STOP: vectors look unit-norm (fine-tuned). Raising in chat.")
        (config.OUTPUTS_DIR / "blockc_report.md").write_text(
            "\n".join(REPORT_LINES), encoding="utf-8")
        return
    emit("- Verdict: BASE vectors confirmed. Proceeding.")
    emit()

    # ------------------------------------------------------------------
    emit("## 1. Visual layer")
    emit()
    inst = ns.kept[ns.kept["format_id"].isin(Fset)].reset_index(drop=True)
    locs = inst["file"].map(fname_to_loc.get)
    missing = locs.isna()
    emit("- 04 instance sample: {} instances across {} formats; vision "
         "vectors found for {} ({}); {} missing (corrupted at extraction "
         "or filename mismatch).".format(
             len(inst), n, int((~missing).sum()),
             A.pct((~missing).sum() / len(inst)), int(missing.sum())))
    emit("- Stated limitation (choice b): the visual layer covers exactly "
         "the 04 instance sample, which is OCR-usable instances only; "
         "vision-only instances (no usable text) are excluded by "
         "construction.")

    by_chunk = defaultdict(list)
    for pos, loc in enumerate(locs):
        if isinstance(loc, tuple):
            by_chunk[loc[0]].append((loc[1], pos))
    V = np.zeros((len(inst), 768), np.float32)
    have = np.zeros(len(inst), bool)
    for ci, pairs in sorted(by_chunk.items()):
        arr = np.load(emb_files[ci], mmap_mode="r")
        rows = np.array([r for r, _ in pairs])
        poss = np.array([p for _, p in pairs])
        order = np.argsort(rows)
        V[poss[order]] = np.asarray(arr[rows[order]])
        have[poss] = True
    nv = np.linalg.norm(V, axis=1, keepdims=True)
    nv[nv == 0] = 1.0
    V = V / nv  # L2-normalise instance vectors before averaging (choice c/b)

    fmt_rows = np.array([ns.fid_index[f] for f in inst["format_id"]])
    C = np.zeros((n, 768), np.float32)
    cnt = np.zeros(n, np.float32)
    np.add.at(C, fmt_rows[have], V[have])
    np.add.at(cnt, fmt_rows[have], 1.0)
    cap_counts = inst.groupby("format_id").size()
    full_match = sum(1 for f in ns.F
                     if int(cnt[ns.fid_index[f]]) == int(cap_counts[f]))
    emit("- Per-format vision counts equal the 04 capped counts for {} of "
         "{} formats (shortfalls are the missing vectors above); min/median/"
         "max vectors per format {:.0f}/{:.0f}/{:.0f}.".format(
             full_match, n, cnt.min(), np.median(cnt), cnt.max()))
    Cn = C / np.maximum(cnt[:, None], 1.0)
    S_vis = A.cosine_matrix(Cn)
    vis_v = S_vis[iu].astype(np.float64)

    # per-format coherence (choice c): mean cosine of instances to own
    # (normalised) centroid
    cent_unit = Cn / np.maximum(np.linalg.norm(Cn, axis=1, keepdims=True), 1e-9)
    coh_sum = np.zeros(n, np.float64)
    dots = (V[have] * cent_unit[fmt_rows[have]]).sum(1)
    np.add.at(coh_sum, fmt_rows[have], dots)
    coherence = coh_sum / np.maximum(cnt, 1.0)

    # content layer regenerated for the completing regression + context
    # (deterministic; same code path and inputs as Block B)
    from sentence_transformers import SentenceTransformer
    model = SentenceTransformer(config.CONTENT_MODEL, device="cuda")
    log("  re-encoding content embeddings (deterministic Block B repeat)...")
    emb = model.encode(inst["text_stripped"].tolist(), batch_size=256,
                       convert_to_numpy=True, normalize_embeddings=True
                       ).astype(np.float32)
    Cc = np.zeros((n, emb.shape[1]), np.float32)
    np.add.at(Cc, fmt_rows, emb)
    Cc = Cc / np.maximum(np.bincount(fmt_rows, minlength=n)[:, None], 1.0)
    S_content = A.cosine_matrix(Cc)
    content_v = S_content[iu].astype(np.float64)

    from scipy.stats import spearmanr
    emit("- Context (baseline coupling): Spearman visual vs content = "
         "{:.4f}; vs fw_negjsd = {:.4f}; vs pos_cosine = {:.4f}.".format(
             spearmanr(vis_v, content_v).correlation,
             spearmanr(vis_v, pc.y_v["fw_negjsd"]).correlation,
             spearmanr(vis_v, pc.y_v["pos_cosine"]).correlation))
    emit()

    # combined permutation loop: visual omnibus + per-family one-vs-rest +
    # completing-regression betas
    Z3 = np.column_stack([np.ones(len(vis_v)), content_v, vis_v,
                          pc.stype_v.astype(np.float64),
                          pc.lsum_v.astype(np.float64)])
    Z3inv = np.linalg.pinv(Z3)
    ey3 = {meas: pc.y_v[meas] - Z3 @ (Z3inv @ pc.y_v[meas])
           for meas in ("fw_negjsd", "pos_cosine")}
    Zc = np.column_stack([np.ones(len(vis_v)), vis_v,
                          pc.stype_v.astype(np.float64),
                          pc.lsum_v.astype(np.float64)])
    Zcinv = np.linalg.pinv(Zc)
    eyc = content_v - Zc @ (Zcinv @ content_v)

    FORM_REG = [("EVALUATE", "fw_negjsd"), ("EVALUATE", "pos_cosine"),
                ("LABEL", "fw_negjsd"), ("LABEL", "pos_cosine")]
    CONT_REG = ["EXPRESS", "LABEL"]

    def fwl(m_v, Zi, Zinv, ey):
        ex = m_v - Zi @ (Zinv @ m_v)
        d = float(ex @ ex)
        return float(ex @ ey) / d if d else np.nan

    def c_stats(Lc):
        out = {}
        M = (Lc @ Lc.T) > 0
        out[("omnibus", "visual")] = A.headline_stat(S_vis, M, n)[0]
        for j, fam in fam_list:
            a = Lc[:, j]
            mw, mb, _, _ = A.pair_means(S_vis, a)
            out[(fam, "visual")] = mw - mb
            ab = a > 0
            w = (ab[i_idx] & ab[j_idx]).astype(np.float64)
            if (fam, "fw_negjsd") in [(f, m) for f, m in FORM_REG]:
                out[(fam, "reg_fw")] = fwl(w, Z3, Z3inv, ey3["fw_negjsd"])
                out[(fam, "reg_pos")] = fwl(w, Z3, Z3inv, ey3["pos_cosine"])
            if fam in CONT_REG:
                out[(fam, "reg_content")] = fwl(w, Zc, Zcinv, eyc)
        return out

    obs = c_stats(L)
    nulls = {k: np.empty(NP_, np.float32) for k in obs}
    rng = np.random.default_rng(config.RANDOM_SEED)
    for t in range(NP_):
        st = c_stats(L[rng.permutation(n)])
        for k, v in st.items():
            nulls[k][t] = v
        if (t + 1) % 2000 == 0:
            print("  block perms {}/{}".format(t + 1, NP_))

    emit("### Visual-layer contrasts (one-vs-rest on centroid cosine)")
    emit()
    CONFIRMATORY = {"EXPRESS", "RESPOND"}
    emit("| Contrast | Effect | p_upper | p_lower | p_twosided | Status |")
    emit("|----------|--------|---------|---------|------------|--------|")
    o = obs[("omnibus", "visual")]
    pu, pl, p2 = grid_row("(omnibus)", "visual_cosine", o,
                          nulls[("omnibus", "visual")], "one_vs_rest")
    emit("| omnibus | {:.5f} | {:.4f} | {:.4f} | {:.4f} | exploratory |".format(
        o, pu, pl, p2))
    for j, fam in fam_list:
        o = obs[(fam, "visual")]
        status = ("confirmatory one-sided" if fam in CONFIRMATORY
                  else "exploratory two-sided")
        pu, pl, p2 = grid_row(fam, "visual_cosine", o, nulls[(fam, "visual")],
                              "one_vs_rest", status)
        emit("| {} | {:.5f} | {:.4f} | {:.4f} | {:.4f} | {} |".format(
            fam, o, pu, pl, p2, status.split(" ")[0]))
    jd = A.FAMILIES.index("DIRECT")
    if L[:, jd].sum() >= 2:
        mw, mb, nw, nb = A.pair_means(S_vis, L[:, jd])
        emit("| DIRECT (descriptive) | {:.5f} | - | - | - | within {:.5f} "
             "vs between {:.5f} (n={}/{}) |".format(mw - mb, mw, mb, nw, nb))
    emit()

    # completed grid (form + content rows from Block B's committed grid)
    bb = pd.read_csv(config.OUTPUTS_DIR / "blockb_grid.csv")
    bb1 = bb[bb["kind"] == "one_vs_rest"]
    emit("### The completed family x layer grid")
    emit()
    emit("| Family | FW (p2) | POS (p2) | Content (p2) | Visual (p2) |")
    emit("|--------|---------|----------|--------------|-------------|")
    for j, fam in fam_list:
        cells = []
        for lay in ("fw_negjsd", "pos_cosine", "content_cosine"):
            r = bb1[(bb1["family"] == fam) & (bb1["layer"] == lay)].iloc[0]
            cells.append("{:+.4f} ({:.4f})".format(
                float(r["effect"]), float(r["p_twosided"])))
            GRID_ROWS.append({
                "family": fam, "layer": lay, "kind": "one_vs_rest",
                "effect": r["effect"], "p_upper": r["p_upper"],
                "p_lower": r["p_lower"], "p_twosided": r["p_twosided"],
                "note": "from blockb_grid.csv"})
        o = obs[(fam, "visual")]
        _, _, p2 = three_ps(o, nulls[(fam, "visual")])
        cells.append("{:+.4f} ({:.4f})".format(o, p2))
        emit("| {} | {} | {} | {} | {} |".format(fam, *cells))
    emit()

    # ------------------------------------------------------------------
    emit("## 2. Gallery-noise robustness")
    emit()
    q = np.quantile(coherence, [0, 0.25, 0.5, 0.75, 1.0])
    emit("- Per-format visual coherence (mean instance-to-own-centroid "
         "cosine): min {:.3f} / q25 {:.3f} / median {:.3f} / q75 {:.3f} / "
         "max {:.3f}.".format(*q))
    emit()
    emit("Coherence by family (descriptive means):")
    emit()
    emit("| Family | Formats | Mean coherence |")
    emit("|--------|---------|----------------|")
    for j, fam in enumerate(A.FAMILIES):
        a = L[:, j] > 0
        if a.sum() >= 2:
            emit("| {} | {} | {:.4f} |".format(fam, int(a.sum()),
                                               coherence[a].mean()))
    emit()
    emit("Coherence by Type (descriptive; >= 20 formats):")
    emit()
    emit("| Type | Formats | Mean coherence |")
    emit("|------|---------|----------------|")
    from collections import Counter as Ctr
    tfreq = Ctr(t for ts in ns.type_sets for t in ts)
    trows = []
    for t, k in tfreq.items():
        if k < 20:
            continue
        m = np.array([t in ts for ts in ns.type_sets])
        trows.append((t, int(m.sum()), float(coherence[m].mean())))
    for t, k, mc in sorted(trows, key=lambda x: -x[2]):
        emit("| {} | {} | {:.4f} |".format(t, k, mc))
    emit()

    med = np.median(coherence)
    high = coherence > med
    hi_idx = np.where(high)[0]
    emit("Restriction: high-coherence half = coherence > population median "
         "({:.4f}); {} formats.".format(med, len(hi_idx)))
    emit()

    SIG_CELLS = [("EVALUATE", "fw_negjsd"), ("EVALUATE", "pos_cosine"),
                 ("LABEL", "fw_negjsd"), ("LABEL", "pos_cosine"),
                 ("LABEL", "content_cosine"), ("EXPRESS", "content_cosine"),
                 ("CAPTION", "fw_negjsd"), ("CAPTION", "pos_cosine"),
                 ("CAPTION", "content_cosine")]
    S_by_layer = {"fw_negjsd": ns.S_dict["fw_negjsd"],
                  "pos_cosine": ns.S_dict["pos_cosine"],
                  "content_cosine": S_content}
    Sh = {lay: S[np.ix_(hi_idx, hi_idx)] for lay, S in S_by_layer.items()}
    Lh = L[hi_idx]
    nh = len(hi_idx)

    def r_stats(Lc):
        out = {}
        for fam, lay in SIG_CELLS:
            a = Lc[:, A.FAMILIES.index(fam)]
            if a.sum() < 2:
                out[(fam, lay)] = np.nan
                continue
            mw, mb, _, _ = A.pair_means(Sh[lay], a)
            out[(fam, lay)] = mw - mb
        return out

    r_obs = r_stats(Lh)
    r_nulls = {k: np.empty(NP_, np.float32) for k in r_obs}
    rrng = np.random.default_rng(config.RANDOM_SEED)
    for t in range(NP_):
        st = r_stats(Lh[rrng.permutation(nh)])
        for k, v in st.items():
            r_nulls[k][t] = v
        if (t + 1) % 2000 == 0:
            print("  restriction perms {}/{}".format(t + 1, NP_))

    emit("Reading rule (recorded in advance): effects that hold or "
         "strengthen under restriction were diluted by gallery noise (full "
         "results conservative); effects that vanish are flagged as possible "
         "mixed-gallery artefacts and discussed in chat before drafting.")
    emit()
    emit("| Cell | Full effect | Restricted effect | p_upper | p_lower | "
         "p_twosided | Within-pairs (restr.) | Reading |")
    emit("|------|-------------|-------------------|---------|---------|"
         "------------|-----------------------|---------|")
    full_eff = {}
    for fam, lay in SIG_CELLS:
        r = bb1[(bb1["family"] == fam) & (bb1["layer"] == lay)].iloc[0]
        full_eff[(fam, lay)] = float(r["effect"])
    for fam, lay in SIG_CELLS:
        o = r_obs[(fam, lay)]
        pu, pl, p2 = grid_row(fam, lay, o, r_nulls[(fam, lay)],
                              "high_coherence_restricted")
        a = Lh[:, A.FAMILIES.index(fam)]
        k = a.sum()
        nwp = int(k * (k - 1) / 2)
        fe = full_eff[(fam, lay)]
        same_sign = (o > 0) == (fe > 0)
        stronger = abs(o) >= abs(fe)
        sig = (p2 == p2 and p2 < 0.05)
        if sig and same_sign:
            reading = "holds" + (" (strengthens)" if stronger else "")
        elif same_sign:
            reading = "attenuates (n.s. restricted)"
        else:
            reading = "FLAG: sign flip"
        flag = " *<100*" if nwp < config.MIN_PAIRS_FLAG else ""
        emit("| {} {} | {:+.5f} | {:+.5f} | {:.4f} | {:.4f} | {:.4f} | {}{} | {} |".format(
            fam, lay, fe, o, pu, pl, p2, nwp, flag, reading))
    emit()

    # ------------------------------------------------------------------
    emit("## 3. Completing regressions (one model per protected cell)")
    emit()
    emit("| Cell | Model | within_family beta | p_upper | p_lower | p_twosided |")
    emit("|------|-------|--------------------|---------|---------|------------|")
    for fam, meas in FORM_REG:
        key = (fam, "reg_fw" if meas == "fw_negjsd" else "reg_pos")
        o = obs[key]
        pu, pl, p2 = grid_row(fam, meas, o, nulls[key],
                              "mrqap_content_visual_controlled")
        emit("| {} {} | form ~ fam + content + visual + type + size | "
             "{:.5f} | {:.4f} | {:.4f} | {:.4f} |".format(
                 fam, meas, o, pu, pl, p2))
    for fam in CONT_REG:
        o = obs[(fam, "reg_content")]
        pu, pl, p2 = grid_row(fam, "content_cosine", o,
                              nulls[(fam, "reg_content")],
                              "mrqap_visual_controlled")
        emit("| {} content | content ~ fam + visual + type + size | "
             "{:.5f} | {:.4f} | {:.4f} | {:.4f} |".format(fam, o, pu, pl, p2))
    emit()

    # ------------------------------------------------------------------
    # figures
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fams = [fam for _, fam in fam_list]
    layers = ["fw_negjsd", "pos_cosine", "content_cosine", "visual_cosine"]
    gdf = pd.DataFrame(GRID_ROWS)
    Gm = np.zeros((len(fams), 4))
    Pm = np.zeros((len(fams), 4))
    for r_i, fam in enumerate(fams):
        for c_i, lay in enumerate(layers):
            row = gdf[(gdf["family"] == fam) & (gdf["layer"] == lay) &
                      (gdf["kind"] == "one_vs_rest")].iloc[0]
            Gm[r_i, c_i] = float(row["effect"])
            Pm[r_i, c_i] = float(row["p_twosided"])
    fig, ax = plt.subplots(figsize=(8.5, 4.5))
    vm = np.abs(Gm).max()
    im = ax.imshow(Gm, cmap="RdBu_r", vmin=-vm, vmax=vm)
    ax.set_xticks(range(4))
    ax.set_xticklabels(["FW (-JSD)", "POS trigram", "Content (bge)",
                        "Visual (SigLIP)"])
    ax.set_yticks(range(len(fams)))
    ax.set_yticklabels(fams)
    for r_i in range(len(fams)):
        for c_i in range(4):
            ax.text(c_i, r_i, "{:+.3f}\np2={:.3f}".format(Gm[r_i, c_i],
                                                          Pm[r_i, c_i]),
                    ha="center", va="center", fontsize=7)
    ax.set_title("One-vs-rest effects: the completed family x layer grid")
    fig.colorbar(im, shrink=0.8)
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(figs / ("blockc_grid_heatmap." + ext), dpi=200)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.hist(coherence, bins=60, color="tab:green", alpha=0.8)
    for v, lab in ((q[1], "q25"), (q[2], "median"), (q[3], "q75")):
        ax.axvline(v, color="black", ls="--", lw=0.8)
        ax.text(v, ax.get_ylim()[1] * 0.95, lab, fontsize=7, ha="center")
    ax.set_xlabel("per-format visual coherence (mean cosine to own centroid)")
    ax.set_ylabel("formats")
    ax.set_title("Visual coherence distribution (n={})".format(n))
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(figs / ("blockc_coherence." + ext), dpi=200)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 4.5))
    labels = ["{}\n{}".format(f, l.replace("_cosine", "").replace(
        "fw_negjsd", "FW").replace("pos_cosine", "POS")) for f, l in SIG_CELLS]
    xs = np.arange(len(SIG_CELLS))
    ax.scatter(xs - 0.12, [full_eff[c] for c in SIG_CELLS], marker="o",
               color="tab:blue", label="full population")
    ax.scatter(xs + 0.12, [r_obs[c] for c in SIG_CELLS], marker="s",
               color="tab:red", label="high-coherence half")
    ax.axhline(0, color="black", lw=0.5)
    ax.set_xticks(xs)
    ax.set_xticklabels(labels, fontsize=7)
    ax.set_ylabel("one-vs-rest effect")
    ax.set_title("Significant grid cells: full vs high-coherence restriction")
    ax.legend(fontsize=8)
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(figs / ("blockc_restriction." + ext), dpi=200)
    plt.close(fig)
    emit("Figures: blockc_grid_heatmap, blockc_coherence, blockc_restriction "
         "(PDF+PNG).")
    emit()
    emit("Decision point C - final scope call and exhibits planning - "
         "happens in chat.")

    pd.DataFrame(GRID_ROWS).to_csv(config.OUTPUTS_DIR / "blockc_grid.csv",
                                   index=False, encoding="utf-8")
    emit()
    emit("Wrote outputs/blockc_grid.csv ({} rows; supersedes blockb_grid.csv "
         "as the central table, B file untouched for provenance).".format(
             len(GRID_ROWS)))
    (config.OUTPUTS_DIR / "blockc_report.md").write_text(
        "\n".join(REPORT_LINES), encoding="utf-8")
    print("Report written to outputs/blockc_report.md")


if __name__ == "__main__":
    main()
