"""04f_denoise.py - instance-level gallery denoising per 04F_DENOISE_SPEC.md.

Run: python scripts/04f_denoise.py
Replaces the format-level coherence approach (04D section 2 / 04E) with
direct removal of off-template instances, then retests the significant grid
cells. 04E's composition findings stand as supporting evidence; this is the
primary noise answer.

Choice (a) verification (recorded in the report): the Chapter-3 inference
path (SigLIPWithProjection.encode_image) feeds RAW vision pooler_output -
exactly the stored base chunks - into the projection with no preprocessing;
checkpoint shapes match ProjectionHead(768->3072->3072->768) with BatchNorm
running statistics, dropout 0 at inference, output L2-normalised by the
head's forward. The head therefore applies cleanly to the stored features.

Recorded caveats (design log): SigLIP embeds rendered text strongly, so
typicality partly tracks text content (text-in-image sensitivity); formats
whose galleries mix sibling templates can have genuine instances scored as
atypical (sibling-template bleed).
"""
import importlib
import json
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))
import config

A = importlib.import_module("04_analysis")

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

REPORT_LINES = []
RETEST_ROWS = []
TEXT_ANCHORED = ("catchphrase", "copypasta", "snowclone", "slang")
PAIR_CELLS = [("EVALUATE", "fw"), ("EVALUATE", "pos"),
              ("LABEL", "fw"), ("LABEL", "pos"), ("LABEL", "content"),
              ("EXPRESS", "content"),
              ("CAPTION", "fw"), ("CAPTION", "pos"), ("CAPTION", "content")]
LAYER_KEY = {"fw": "fw_negjsd", "pos": "pos_cosine",
             "content": "content_cosine"}


def emit(line=""):
    print(line)
    REPORT_LINES.append(line)


def log(line=""):
    print(line)


def three_ps(obs, null):
    null = np.asarray(null, dtype=np.float64)
    null = null[~np.isnan(null)]
    if obs != obs or not len(null):
        return np.nan, np.nan, np.nan
    np1 = len(null) + 1.0
    return ((1.0 + (null >= obs).sum()) / np1,
            (1.0 + (null <= obs).sum()) / np1,
            (1.0 + (np.abs(null) >= abs(obs)).sum()) / np1)


def main():
    figs = config.OUTPUTS_DIR / "figures"
    figs.mkdir(parents=True, exist_ok=True)

    emit("# Block F report: instance-level gallery denoising "
         "(04F_DENOISE_SPEC.md)")
    emit()
    emit("Generated by scripts/04f_denoise.py on {} with seed {}; "
         "N_PERMUTATIONS={}; k={}, primary percentile {}, sensitivity {}, "
         "min gallery {}.".format(
             datetime.now().strftime("%Y-%m-%d %H:%M"), config.RANDOM_SEED,
             config.N_PERMUTATIONS, config.DENOISE_K,
             config.DENOISE_PCTL_PRIMARY, config.DENOISE_PCTL_SENS,
             config.DENOISE_MIN_GALLERY))
    emit()

    ns = A.prepare(log)
    if ns is None:
        return
    n, L = ns.n, ns.L
    NP_ = config.N_PERMUTATIONS
    Fset = set(ns.F)

    # ------------------------------------------------------------------
    emit("## Choice (a) verification")
    emit()
    import torch
    import torch.nn as nn
    import torch.nn.functional as F_t

    class ProjectionHead(nn.Module):
        """Mirror of SemioMeme config/models.py ProjectionHead."""

        def __init__(self, input_dim=768, hidden_dim=3072, output_dim=768,
                     dropout=0.0):
            super().__init__()
            self.layers = nn.Sequential(
                nn.Linear(input_dim, hidden_dim),
                nn.BatchNorm1d(hidden_dim), nn.ReLU(), nn.Dropout(dropout),
                nn.Linear(hidden_dim, hidden_dim),
                nn.BatchNorm1d(hidden_dim), nn.ReLU(), nn.Dropout(dropout),
                nn.Linear(hidden_dim, output_dim), nn.BatchNorm1d(output_dim))
            self.alpha = nn.Parameter(torch.tensor(0.0))

        def forward(self, x):
            t = self.layers(x)
            out = t + self.alpha * x if float(self.alpha) > 0 else t
            return F_t.normalize(out, p=2, dim=1)

    ck = torch.load(config.VISION_FT_CHECKPOINT, map_location="cpu")
    cfg = ck.get("config", {})
    head = ProjectionHead(cfg.get("input_dim", 768), cfg.get("hidden_dim", 3072),
                          cfg.get("output_dim", 768), dropout=0.0)
    head.load_state_dict(ck["model_state_dict"])
    head.eval().cuda()
    emit("- Checkpoint: {} (epoch {}, val_accuracy {}). Input dim {} matches "
         "the stored 768-d base pooler outputs; the Chapter-3 inference path "
         "feeds them RAW (no pre-normalisation); dropout 0, BatchNorm in "
         "eval mode (running stats), alpha = {:.4f}; output L2-normalised "
         "by forward. Applies cleanly - proceeding.".format(
             config.VISION_FT_CHECKPOINT.name, ck.get("epoch", "?"),
             round(float(ck.get("val_accuracy", float("nan"))), 4),
             cfg.get("input_dim", 768), float(head.alpha)))
    emit()

    # base vectors for the 04 sample (raw - the head's expected input)
    meta_files = sorted(config.VISION_METADATA_DIR.glob("metadata_chunk_*.json"))
    emb_files = sorted(config.VISION_EMBEDDINGS_DIR.glob("embeddings_chunk_*.npy"))
    fname_to_loc = {}
    for ci, mf in enumerate(meta_files):
        m = json.loads(Path(mf).read_text())
        for ri, im in enumerate(m["valid_images"]):
            fname_to_loc[im["filename"]] = (ci, ri)
    inst = ns.kept[ns.kept["format_id"].isin(Fset)].reset_index(drop=True)
    locs = inst["file"].map(fname_to_loc.get)
    by_chunk = defaultdict(list)
    for pos, loc in enumerate(locs):
        if isinstance(loc, tuple):
            by_chunk[loc[0]].append((loc[1], pos))
    Vraw = np.zeros((len(inst), 768), np.float32)
    for ci, pairs in sorted(by_chunk.items()):
        arr = np.load(emb_files[ci], mmap_mode="r")
        rows = np.array([r for r, _ in pairs])
        poss = np.array([p for _, p in pairs])
        order = np.argsort(rows)
        Vraw[poss[order]] = np.asarray(arr[rows[order]])

    with torch.no_grad():
        outs = []
        for i0 in range(0, len(Vraw), 2048):
            x = torch.from_numpy(Vraw[i0:i0 + 2048]).cuda()
            outs.append(head(x).cpu().numpy())
    E_ft = np.vstack(outs).astype(np.float32)
    E_base = Vraw / np.maximum(np.linalg.norm(Vraw, axis=1, keepdims=True), 1e-9)

    fmt_rows = np.array([ns.fid_index[f] for f in inst["format_id"]])
    fmt_groups = defaultdict(list)
    for pos, r in enumerate(fmt_rows):
        fmt_groups[r].append(pos)

    def typicality(E):
        typ = np.full(len(inst), np.nan)
        for r, poss in fmt_groups.items():
            if len(poss) < config.DENOISE_MIN_GALLERY:
                continue  # exempt: too few neighbours to judge
            G = E[poss]
            S = G @ G.T
            np.fill_diagonal(S, -np.inf)
            k = config.DENOISE_K
            part = np.partition(S, -k, axis=1)[:, -k:]
            typ[poss] = part.mean(1)
        return typ

    typ_ft = typicality(E_ft)
    typ_base = typicality(E_base)
    scored = ~np.isnan(typ_ft)
    p10 = np.percentile(typ_ft[scored], config.DENOISE_PCTL_PRIMARY)
    p20 = np.percentile(typ_ft[scored], config.DENOISE_PCTL_SENS)
    removed_p10 = scored & (typ_ft < p10)
    removed_p20 = scored & (typ_ft < p20)
    scored_b = ~np.isnan(typ_base)
    p10_b = np.percentile(typ_base[scored_b], config.DENOISE_PCTL_PRIMARY)
    removed_base = scored_b & (typ_base < p10_b)

    # ------------------------------------------------------------------
    emit("## 1. Denoising pass")
    emit()
    qs = np.percentile(typ_ft[scored], [0, 25, 50, 75, 100])
    emit("- Typicality (fine-tuned space, k={} NN within own gallery): "
         "min {:.4f} / q25 {:.4f} / median {:.4f} / q75 {:.4f} / max {:.4f}; "
         "{} of {} instances scored ({} exempt in galleries < {}).".format(
             config.DENOISE_K, *qs, int(scored.sum()), len(inst),
             int((~scored).sum()), config.DENOISE_MIN_GALLERY))
    emit("- Removal: {} instances ({}) below the {}th-percentile cut "
         "{:.4f}; sensitivity {}th percentile removes {} ({}).".format(
             int(removed_p10.sum()), A.pct(removed_p10.sum() / len(inst)),
             config.DENOISE_PCTL_PRIMARY, p10,
             config.DENOISE_PCTL_SENS, int(removed_p20.sum()),
             A.pct(removed_p20.sum() / len(inst))))
    emit()
    emit("Removal rate by Type (primary threshold; instance level):")
    emit()
    emit("| Type | Instances | Removed | Rate | Flag (>25% text-anchored) |")
    emit("|------|-----------|---------|------|---------------------------|")
    from collections import Counter as Ctr
    tfreq = Ctr(t for ts in ns.type_sets for t in ts)
    flagged_types = []
    for t, kf in sorted(tfreq.items(), key=lambda x: -x[1]):
        if kf < 20:
            continue
        fmask = np.array([t in ns.type_sets[r] for r in fmt_rows])
        ni, nr = int(fmask.sum()), int((fmask & removed_p10).sum())
        rate = nr / ni if ni else 0.0
        fl = ""
        if t in TEXT_ANCHORED and rate > 0.25:
            fl = "FLAGGED"
            flagged_types.append(t)
        emit("| {}{} | {} | {} | {} | {} |".format(
            t, " (text-anchored)" if t in TEXT_ANCHORED else "",
            ni, nr, A.pct(rate), fl))
    emit()
    if flagged_types:
        emit("FLAG for chat before interpretation: text-anchored Type(s) "
             "with > 25% removal at the primary threshold: {}.".format(
                 ", ".join(flagged_types)))
    else:
        emit("No text-anchored Type exceeds 25% removal at the primary "
             "threshold; choice (d) flag not triggered.")
    emit()
    emit("Removal rate by family-carrier status (primary):")
    emit()
    emit("| Family | Instances in carriers | Removed | Rate |")
    emit("|--------|----------------------|---------|------|")
    for j, fam in enumerate(A.FAMILIES):
        cmask = L[fmt_rows, j] > 0
        ni, nr = int(cmask.sum()), int((cmask & removed_p10).sum())
        if ni:
            emit("| {} | {} | {} | {} |".format(fam, ni, nr, A.pct(nr / ni)))
    emit()

    rng = np.random.default_rng(config.RANDOM_SEED)
    emit("### Removed-instance sample (40, seeded)")
    emit()
    rem_idx = np.where(removed_p10)[0]
    for i in rng.choice(rem_idx, size=min(40, len(rem_idx)), replace=False):
        emit("- [{:.3f}] {} :: {}".format(
            typ_ft[i], ns.titles[fmt_rows[i]],
            " ".join(str(inst["text_stripped"].iloc[i]).split())[:160]))
    emit()
    emit("### Retained-instance sample (40, seeded)")
    emit()
    ret_idx = np.where(scored & ~removed_p10)[0]
    for i in rng.choice(ret_idx, size=min(40, len(ret_idx)), replace=False):
        emit("- [{:.3f}] {} :: {}".format(
            typ_ft[i], ns.titles[fmt_rows[i]],
            " ".join(str(inst["text_stripped"].iloc[i]).split())[:160]))
    emit()

    # ------------------------------------------------------------------
    # one spaCy pass storing per-instance profiles; all retests aggregate it
    log("  per-instance profile pass (single spaCy run)...")
    inst_fw = [None] * len(inst)
    inst_tri = [None] * len(inst)
    inst_when = np.zeros(len(inst), np.float32)
    for r, poss in fmt_groups.items():
        texts = [inst["text_stripped"].iloc[p] for p in poss]
        _, _, per = ns.profile_texts(texts, True)
        for p, (ifw, itri, cues) in zip(poss, per):
            inst_fw[p] = ifw
            # per-instance trigram counters are keyed by tag tuples;
            # remap to the shared vocabulary indices for aggregation
            inst_tri[p] = {ns.tri_index[g]: c for g, c in itri.items()}
            inst_when[p] = cues[3]
    V_tri = len(ns.tri_index)

    log("  encoding content embeddings (deterministic repeat)...")
    from sentence_transformers import SentenceTransformer
    smodel = SentenceTransformer(config.CONTENT_MODEL, device="cuda")
    bge = smodel.encode(inst["text_stripped"].tolist(), batch_size=256,
                        convert_to_numpy=True, normalize_embeddings=True
                        ).astype(np.float32)

    def build_layers(keep_mask):
        """Format-level FW/POS/content matrices + when-rates from retained
        instances; returns (S_dict, valid_format_mask, when_rate)."""
        fw = np.zeros((n, len(ns.STOP)), np.float64)
        tri = np.zeros((n, V_tri), np.float32)
        cc = np.zeros((n, bge.shape[1]), np.float32)
        ccn = np.zeros(n, np.float32)
        wsum = np.zeros(n, np.float64)
        wcnt = np.zeros(n, np.float64)
        for p in np.where(keep_mask)[0]:
            r = fmt_rows[p]
            for i, c in inst_fw[p].items():
                fw[r, i] += c
            for g, c in inst_tri[p].items():
                tri[r, g] += c
            cc[r] += bge[p]
            ccn[r] += 1
            wsum[r] += inst_when[p]
            wcnt[r] += 1
        valid = fw.sum(1) > 0
        Pm = fw / np.maximum(fw.sum(1, keepdims=True), 1e-9)
        Xm = tri / np.maximum(tri.sum(1, keepdims=True), 1e-9)
        Cm = cc / np.maximum(ccn[:, None], 1.0)
        S = {"fw": A.neg_jsd_matrix(Pm), "pos": A.cosine_matrix(Xm),
             "content": A.cosine_matrix(Cm)}
        when_rate = np.where(wcnt > 0, wsum / np.maximum(wcnt, 1), np.nan)
        return S, valid, when_rate

    def retest(keep_mask, tag, with_perms):
        S, valid, when_rate = build_layers(keep_mask)
        vidx = np.where(valid)[0]
        Lv = L[vidx]
        nv = len(vidx)
        Sv = {lay: M[np.ix_(vidx, vidx)] for lay, M in S.items()}

        def stats(Lc):
            o = {}
            for fam, lay in PAIR_CELLS:
                a = Lc[:, A.FAMILIES.index(fam)]
                if a.sum() < 2:
                    o[(fam, lay)] = np.nan
                    continue
                mw, mb, _, _ = A.pair_means(Sv[lay], a)
                o[(fam, lay)] = mw - mb
            return o

        obs = stats(Lv)
        ps = {k: (np.nan, np.nan, np.nan) for k in obs}
        if with_perms:
            nulls = {k: np.empty(NP_, np.float32) for k in obs}
            prng = np.random.default_rng(config.RANDOM_SEED)
            for t in range(NP_):
                st = stats(Lv[prng.permutation(nv)])
                for k, v in st.items():
                    nulls[k][t] = v
                if (t + 1) % 2000 == 0:
                    print("  {} perms {}/{}".format(tag, t + 1, NP_))
            ps = {k: three_ps(obs[k], nulls[k]) for k in obs}

        # RESPOND when-clause cell: carrier vs non-carrier diff, bootstrap CI
        jr = A.FAMILIES.index("RESPOND")
        a = (L[:, jr] > 0) & valid & ~np.isnan(when_rate)
        b = (L[:, jr] == 0) & valid & ~np.isnan(when_rate)
        va, vb = when_rate[a], when_rate[b]
        brng = np.random.default_rng(config.RANDOM_SEED)
        bd = [va[brng.integers(0, len(va), len(va))].mean()
              - vb[brng.integers(0, len(vb), len(vb))].mean()
              for _ in range(config.BOOTSTRAP_N)]
        wlo, whi = np.quantile(bd, [0.025, 0.975])
        when = (float(va.mean() - vb.mean()), float(wlo), float(whi))
        return obs, ps, when, nv, int(valid.sum())

    emit("## 2. Retest (primary threshold, fine-tuned space)")
    emit()
    obs_p, ps_p, when_p, nv_p, _ = retest(~removed_p10, "primary", True)
    obs_s, _, when_s, _, _ = retest(~removed_p20, "sens", False)
    full_when_obs, _, full_when, _, _ = retest(np.ones(len(inst), bool),
                                               "full", False)

    # full-data pair-cell numbers from the committed grids
    blocka = pd.read_csv(config.OUTPUTS_DIR / "blocka_inference.csv")
    blockb = pd.read_csv(config.OUTPUTS_DIR / "blockb_grid.csv")
    bb1 = blockb[blockb["kind"] == "one_vs_rest"]

    def full_cell(fam, lay):
        if lay == "content":
            r = bb1[(bb1["family"] == fam) &
                    (bb1["layer"] == "content_cosine")].iloc[0]
            return float(r["effect"]), float(r["p_twosided"])
        r = blocka[(blocka["contrast"] == "fam_" + fam) &
                   (blocka["measure"] == LAYER_KEY[lay])].iloc[0]
        return float(r["effect"]), float(r["p_twosided"])

    emit("| Cell | Full effect (p2) | Denoised effect | p_up | p_lo | p_2 | "
         "Sens. ({}th) effect | Verdict |".format(config.DENOISE_PCTL_SENS))
    emit("|------|------------------|-----------------|------|------|-----|"
         "---------------------|---------|")
    verdicts = {}
    for fam, lay in PAIR_CELLS:
        fe, fp2 = full_cell(fam, lay)
        o = obs_p[(fam, lay)]
        pu, pl, p2 = ps_p[(fam, lay)]
        sig = p2 == p2 and p2 < 0.05 and (o > 0) == (fe > 0)
        verdict = "holds" if sig else "LOSES significance - qualify"
        verdicts[(fam, lay)] = verdict
        RETEST_ROWS.append({
            "cell": "{}_{}".format(fam, lay), "full_effect": fe,
            "full_p2": fp2, "denoised_effect": round(float(o), 6),
            "p_upper": round(pu, 6), "p_lower": round(pl, 6),
            "p_twosided": round(p2, 6),
            "sens_effect": round(float(obs_s[(fam, lay)]), 6),
            "verdict": verdict})
        emit("| {} {} | {:+.5f} ({:.4f}) | {:+.5f} | {:.4f} | {:.4f} | "
             "{:.4f} | {:+.5f} | {} |".format(
                 fam, lay, fe, fp2, o, pu, pl, p2, obs_s[(fam, lay)], verdict))
    emit("| RESPOND when-clause | {:+.4f} [{:+.4f}, {:+.4f}] | {:+.4f} "
         "[{:+.4f}, {:+.4f}] | - | - | - | {:+.4f} | {} |".format(
             full_when[0], full_when[1], full_when[2],
             when_p[0], when_p[1], when_p[2], when_s[0],
             "holds" if when_p[1] > 0 else "LOSES significance - qualify"))
    RETEST_ROWS.append({
        "cell": "RESPOND_when_clause", "full_effect": round(full_when[0], 6),
        "full_p2": "", "denoised_effect": round(when_p[0], 6),
        "p_upper": "", "p_lower": "", "p_twosided": "",
        "sens_effect": round(when_s[0], 6),
        "verdict": "holds (CI excludes 0)" if when_p[1] > 0
        else "LOSES significance - qualify"})
    emit()
    emit("Reading rule (fixed in the spec): cells holding under denoising "
         "are reported with the denoised analysis as a robustness "
         "paragraph; any cell losing significance at the primary threshold "
         "is flagged and the full-data claim is qualified in the paper. No "
         "within-format coherence argument is made from this block in "
         "either direction.")
    emit()

    # ------------------------------------------------------------------
    emit("## 3. Robustness variant (base embeddings for typicality)")
    emit()
    inter = int((removed_p10 & removed_base).sum())
    union = int((removed_p10 | removed_base).sum())
    emit("- Removed sets: fine-tuned {} vs base {}; overlap Jaccard = "
         "{:.3f}.".format(int(removed_p10.sum()), int(removed_base.sum()),
                          inter / union if union else float("nan")))
    obs_b, ps_b, when_b, _, _ = retest(~removed_base, "base", True)
    emit()
    emit("| Cell | Denoised (ft) | Denoised (base) | base p_2 | Verdict flip? |")
    emit("|------|---------------|-----------------|----------|---------------|")
    flips = []
    for fam, lay in PAIR_CELLS:
        fe, _ = full_cell(fam, lay)
        ob = obs_b[(fam, lay)]
        _, _, p2b = ps_b[(fam, lay)]
        sigb = p2b == p2b and p2b < 0.05 and (ob > 0) == (fe > 0)
        ft_holds = verdicts[(fam, lay)] == "holds"
        flip = sigb != ft_holds
        if flip:
            flips.append("{} {}".format(fam, lay))
        emit("| {} {} | {:+.5f} | {:+.5f} | {:.4f} | {} |".format(
            fam, lay, obs_p[(fam, lay)], ob, p2b, "YES" if flip else "no"))
    emit()
    if flips:
        emit("VERDICT FLIPS between spaces -> chat: {}.".format(", ".join(flips)))
    else:
        emit("No cell's verdict flips between embedding spaces; divergence "
             "stays in this report, not the paper.")
    emit()

    # ------------------------------------------------------------------
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    cells = PAIR_CELLS
    xs = np.arange(len(cells))
    fig, ax = plt.subplots(figsize=(9, 4.5))
    ax.scatter(xs - 0.2, [full_cell(f, l)[0] for f, l in cells], marker="o",
               color="tab:blue", label="full data")
    ax.scatter(xs, [obs_p[c] for c in cells], marker="s", color="tab:red",
               label="denoised (ft, P{})".format(config.DENOISE_PCTL_PRIMARY))
    ax.scatter(xs + 0.2, [obs_b[c] for c in cells], marker="^",
               color="tab:green", label="denoised (base)")
    ax.scatter(xs + 0.35, [obs_s[c] for c in cells], marker=".",
               color="grey", label="sens. (P{})".format(config.DENOISE_PCTL_SENS))
    ax.axhline(0, color="black", lw=0.5)
    ax.set_xticks(xs)
    ax.set_xticklabels(["{}\n{}".format(f, l) for f, l in cells], fontsize=7)
    ax.set_ylabel("one-vs-rest effect")
    ax.set_title("Significant grid cells: full vs denoised")
    ax.legend(fontsize=8)
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(figs / ("blockf_denoise." + ext), dpi=200)
    plt.close(fig)
    emit("Figure: blockf_denoise (PDF+PNG).")

    pd.DataFrame(RETEST_ROWS).to_csv(
        config.OUTPUTS_DIR / "blockf_retest.csv", index=False, encoding="utf-8")
    emit()
    emit("Wrote outputs/blockf_retest.csv ({} rows).".format(len(RETEST_ROWS)))
    (config.OUTPUTS_DIR / "blockf_report.md").write_text(
        "\n".join(REPORT_LINES), encoding="utf-8")
    print("Report written to outputs/blockf_report.md")


if __name__ == "__main__":
    main()
