"""04g_expansion.py - full-scale rerun and pre-drafting checks per
04G_EXPANSION_SPEC.md.

Run: python scripts/04g_expansion.py
Purposes: (1) remove the 100-instance cap and rerun the grid at full scale
(uncapped sets pass the existing preparation filters and the 04F primary
denoising filter applied to the FULL galleries); (2) close four cheap holes
before drafting (size-precision diagnostic, co-carriage / pure-carrier
contrasts, when-clause Type control, content-space anisotropy).

Decision rule (b), fixed in the spec: if every grid cell agrees with the
capped analysis in sign and significance category, the paper reports the
capped analysis as prespecified primary and the uncapped as the
scale/robustness analysis; any flip goes to chat before drafting.
"""
import importlib
import json
import sys
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))
import config

A = importlib.import_module("04_analysis")

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

REPORT_LINES = []
GRID_ROWS = []
CHECK_ROWS = []
LAYERS = ["fw", "pos", "content", "visual"]
FUNCTION_FAMS = {"EXPRESS", "EVALUATE", "RESPOND", "LABEL", "DIRECT"}
BINDING = {"EXPRESS": "content", "EVALUATE": "pos", "LABEL": "pos"}
FORM_REG = [("EVALUATE", "fw"), ("EVALUATE", "pos"),
            ("LABEL", "fw"), ("LABEL", "pos")]
CONT_REG = ["EXPRESS", "LABEL"]
ANISO_FAMS = ["EXPRESS", "LABEL", "RESPOND", "CAPTION"]
INST_FAMS = ["EXPRESS", "LABEL"]


def emit(line=""):
    print(line)
    REPORT_LINES.append(line)


def log(line=""):
    print(line)


def three_ps(obs, null):
    null = np.asarray(null, dtype=np.float64)
    null = null[~np.isnan(null)]
    if obs != obs or not len(null):
        return np.nan, np.nan, np.nan
    np1 = len(null) + 1.0
    return ((1.0 + (null >= obs).sum()) / np1,
            (1.0 + (null <= obs).sum()) / np1,
            (1.0 + (np.abs(null) >= abs(obs)).sum()) / np1)


def sig_cat(effect, p2):
    if p2 == p2 and p2 < 0.05:
        return "sig+" if effect > 0 else "sig-"
    return "n.s."


def main():
    figs = config.OUTPUTS_DIR / "figures"
    figs.mkdir(parents=True, exist_ok=True)

    emit("# Block G report: full-scale rerun and pre-drafting checks "
         "(04G_EXPANSION_SPEC.md)")
    emit()
    emit("Generated by scripts/04g_expansion.py on {} with seed {}; "
         "N_PERMUTATIONS={}.".format(datetime.now().strftime("%Y-%m-%d %H:%M"),
                                     config.RANDOM_SEED, config.N_PERMUTATIONS))
    emit()

    ns = A.prepare(log)
    if ns is None:
        return
    n, L = ns.n, ns.L
    NP_ = config.N_PERMUTATIONS
    Fset = set(ns.F)

    # ------------------------------------------------------------------
    emit("## 1. Uncapped preparation and denoising funnel")
    emit()
    pool = ns.usable[ns.usable["format_id"].isin(Fset)].copy()
    emit("- Usable instances of the {} population formats (pre-strip): "
         "{}.".format(n, len(pool)))
    pool["text_stripped"] = pool["text_raw"].map(ns.strip_text)
    pool["nts"] = pool["text_stripped"].str.split().str.len()
    kept = pool[pool["nts"] >= config.MIN_TOKENS].reset_index(drop=True)
    emit("- After watermark stripping + re-applied MIN_TOKENS: {} "
         "({} dropped).".format(len(kept), len(pool) - len(kept)))
    cnts = kept.groupby("format_id").size()
    emit("- Instances per format: min {} / median {:.0f} / max {} "
         "(capped run: <= {}).".format(cnts.min(), cnts.median(), cnts.max(),
                                       config.PER_FORMAT_INSTANCE_CAP))

    # 04F primary denoising on the FULL galleries
    import torch
    import torch.nn as nn
    import torch.nn.functional as F_t

    class ProjectionHead(nn.Module):
        def __init__(self, input_dim=768, hidden_dim=3072, output_dim=768):
            super().__init__()
            self.layers = nn.Sequential(
                nn.Linear(input_dim, hidden_dim), nn.BatchNorm1d(hidden_dim),
                nn.ReLU(), nn.Dropout(0.0),
                nn.Linear(hidden_dim, hidden_dim), nn.BatchNorm1d(hidden_dim),
                nn.ReLU(), nn.Dropout(0.0),
                nn.Linear(hidden_dim, output_dim), nn.BatchNorm1d(output_dim))
            self.alpha = nn.Parameter(torch.tensor(0.0))

        def forward(self, x):
            t = self.layers(x)
            out = t + self.alpha * x if float(self.alpha) > 0 else t
            return F_t.normalize(out, p=2, dim=1)

    ck = torch.load(config.VISION_FT_CHECKPOINT, map_location="cpu")
    head = ProjectionHead()
    head.load_state_dict(ck["model_state_dict"])
    head.eval().cuda()

    meta_files = sorted(config.VISION_METADATA_DIR.glob("metadata_chunk_*.json"))
    emb_files = sorted(config.VISION_EMBEDDINGS_DIR.glob("embeddings_chunk_*.npy"))
    fname_to_loc = {}
    for ci, mf in enumerate(meta_files):
        m = json.loads(Path(mf).read_text())
        for ri, im in enumerate(m["valid_images"]):
            fname_to_loc[im["filename"]] = (ci, ri)
    locs = kept["file"].map(fname_to_loc.get)
    by_chunk = defaultdict(list)
    for pos, loc in enumerate(locs):
        if isinstance(loc, tuple):
            by_chunk[loc[0]].append((loc[1], pos))
    Vraw = np.zeros((len(kept), 768), np.float32)
    have_vis = np.zeros(len(kept), bool)
    for ci, pairs in sorted(by_chunk.items()):
        arr = np.load(emb_files[ci], mmap_mode="r")
        rows = np.array([r for r, _ in pairs])
        poss = np.array([p for _, p in pairs])
        order = np.argsort(rows)
        Vraw[poss[order]] = np.asarray(arr[rows[order]])
        have_vis[poss] = True
    emit("- Vision vectors found for {} of {} uncapped instances ({} "
         "missing; missing are exempt from removal).".format(
             int(have_vis.sum()), len(kept), int((~have_vis).sum())))

    with torch.no_grad():
        outs = []
        for i0 in range(0, len(Vraw), 2048):
            outs.append(head(torch.from_numpy(Vraw[i0:i0 + 2048]).cuda())
                        .cpu().numpy())
    E_ft = np.vstack(outs).astype(np.float32)
    del outs

    fmt_rows = np.array([ns.fid_index[f] for f in kept["format_id"]])
    fmt_groups = defaultdict(list)
    for pos, r in enumerate(fmt_rows):
        fmt_groups[r].append(pos)

    typ = np.full(len(kept), np.nan)
    for r, poss in fmt_groups.items():
        poss_v = [p for p in poss if have_vis[p]]
        if len(poss_v) < config.DENOISE_MIN_GALLERY:
            continue
        G = E_ft[poss_v]
        S = G @ G.T
        np.fill_diagonal(S, -np.inf)
        part = np.partition(S, -config.DENOISE_K, axis=1)[:, -config.DENOISE_K:]
        typ[poss_v] = part.mean(1)
    scored = ~np.isnan(typ)
    cut = np.percentile(typ[scored], config.DENOISE_PCTL_PRIMARY)
    removed = scored & (typ < cut)
    retained = ~removed
    emit("- 04F primary filter on FULL galleries (k={}, {}th percentile, "
         "cut {:.4f}): {} removed ({}); {} retained.".format(
             config.DENOISE_K, config.DENOISE_PCTL_PRIMARY, cut,
             int(removed.sum()), A.pct(removed.sum() / len(kept)),
             int(retained.sum())))
    rcnts = pd.Series(fmt_rows[retained]).value_counts()
    emit("- Retained per format: min {} / median {:.0f} / max {}.".format(
        int(rcnts.min()), rcnts.median(), int(rcnts.max())))
    emit()

    # visual centroids from base-normalised retained vectors
    Vb = Vraw / np.maximum(np.linalg.norm(Vraw, axis=1, keepdims=True), 1e-9)
    Cv = np.zeros((n, 768), np.float32)
    cv_n = np.zeros(n, np.float32)
    selv = retained & have_vis
    np.add.at(Cv, fmt_rows[selv], Vb[selv])
    np.add.at(cv_n, fmt_rows[selv], 1.0)
    Cv /= np.maximum(cv_n[:, None], 1.0)
    del Vraw, E_ft, Vb

    # per-instance text profiles (single spaCy pass over retained)
    log("  per-instance profile pass over retained uncapped instances...")
    ridx = np.where(retained)[0]
    inst_fw = {}
    inst_tri = {}
    inst_when = np.zeros(len(kept), np.float32)
    for r, poss in fmt_groups.items():
        rposs = [p for p in poss if retained[p]]
        if not rposs:
            continue
        texts = [kept["text_stripped"].iloc[p] for p in rposs]
        _, _, per = ns.profile_texts(texts, True)
        for p, (ifw, itri, cues) in zip(rposs, per):
            inst_fw[p] = ifw
            inst_tri[p] = {ns.tri_index[g]: c for g, c in itri.items()}
            inst_when[p] = cues[3]
    V_tri = len(ns.tri_index)

    # content embeddings, streamed into centroids + seeded subsample store
    log("  encoding uncapped content embeddings...")
    from sentence_transformers import SentenceTransformer
    smodel = SentenceTransformer(config.CONTENT_MODEL, device="cuda")
    sub_rng = np.random.default_rng(config.RANDOM_SEED)
    sub_pick = set()
    for r, poss in fmt_groups.items():
        rposs = [p for p in poss if retained[p]]
        if rposs:
            take = sub_rng.choice(len(rposs),
                                  size=min(config.INSTANCE_CONTENT_SUBSAMPLE,
                                           len(rposs)), replace=False)
            sub_pick.update(rposs[i] for i in take)
    Cc = np.zeros((n, 1024), np.float32)
    cc_n = np.zeros(n, np.float32)
    Msub = np.zeros((n, 1024), np.float32)
    ms_n = np.zeros(n, np.float32)
    B = 4096
    texts_all = kept["text_stripped"].tolist()
    for i0 in range(0, len(ridx), B):
        block = ridx[i0:i0 + B]
        eb = smodel.encode([texts_all[p] for p in block], batch_size=256,
                           convert_to_numpy=True, normalize_embeddings=True
                           ).astype(np.float32)
        rs = fmt_rows[block]
        np.add.at(Cc, rs, eb)
        np.add.at(cc_n, rs, 1.0)
        in_sub = np.array([p in sub_pick for p in block])
        if in_sub.any():
            np.add.at(Msub, rs[in_sub], eb[in_sub])
            np.add.at(ms_n, rs[in_sub], 1.0)
    Cc /= np.maximum(cc_n[:, None], 1.0)
    Msub /= np.maximum(ms_n[:, None], 1.0)  # UNnormalised mean of unit vecs

    # format-level FW / POS / when from retained instances
    fw = np.zeros((n, len(ns.STOP)), np.float64)
    tri = np.zeros((n, V_tri), np.float32)
    wsum = np.zeros(n, np.float64)
    wcnt = np.zeros(n, np.float64)
    for p in ridx:
        r = fmt_rows[p]
        for i, c in inst_fw[p].items():
            fw[r, i] += c
        for g, c in inst_tri[p].items():
            tri[r, g] += c
        wsum[r] += inst_when[p]
        wcnt[r] += 1
    valid = fw.sum(1) > 0
    vidx = np.where(valid)[0]
    nv = len(vidx)
    emit("- Formats with non-empty uncapped profiles: {} of {}.".format(nv, n))
    emit()

    Pm = (fw / np.maximum(fw.sum(1, keepdims=True), 1e-9))[vidx]
    Xm = (tri / np.maximum(tri.sum(1, keepdims=True), 1e-9))[vidx]
    S_dict = {"fw": A.neg_jsd_matrix(Pm), "pos": A.cosine_matrix(Xm),
              "content": A.cosine_matrix(Cc[vidx]),
              "visual": A.cosine_matrix(Cv[vidx])}
    Ms = Msub[vidx]
    S_inst = (Ms @ Ms.T).astype(np.float32)
    np.fill_diagonal(S_inst, 0.0)
    mu = Cc[vidx].mean(0, keepdims=True)
    Ccen = Cc[vidx] - mu
    S_centred = A.cosine_matrix(Ccen)
    when_rate = np.where(wcnt > 0, wsum / np.maximum(wcnt, 1), np.nan)[vidx]
    Lv = L[vidx]
    type_sets_v = [ns.type_sets[i] for i in vidx]

    iu = np.triu_indices(nv, k=1)
    type_vocab = sorted({t for ts in type_sets_v for t in ts})
    Ty = np.zeros((nv, len(type_vocab)), np.float32)
    tmap = {t: i for i, t in enumerate(type_vocab)}
    for i, ts in enumerate(type_sets_v):
        for t in ts:
            Ty[i, tmap[t]] = 1.0
    stype_v = (((Ty @ Ty.T) > 0).astype(np.float32))[iu]
    log_nv = np.log(np.maximum(
        np.array([rcnts.get(i, 1) for i in vidx], np.float64), 1.0))
    lsum_v = (log_nv[:, None] + log_nv[None, :])[iu]
    content_v = S_dict["content"][iu].astype(np.float64)
    vis_v = S_dict["visual"][iu].astype(np.float64)
    y_form = {m: S_dict[m][iu].astype(np.float64) for m in ("fw", "pos")}

    Z3 = np.column_stack([np.ones(len(content_v)), content_v, vis_v,
                          stype_v.astype(np.float64), lsum_v])
    Z3inv = np.linalg.pinv(Z3)
    ey3 = {m: y_form[m] - Z3 @ (Z3inv @ y_form[m]) for m in y_form}
    Zc = np.column_stack([np.ones(len(vis_v)), vis_v,
                          stype_v.astype(np.float64), lsum_v])
    Zcinv = np.linalg.pinv(Zc)
    eyc = content_v - Zc @ (Zcinv @ content_v)

    # when-clause Type control scaffolding (Types with >= 20 valid formats)
    big_types = [t for t in type_vocab
                 if sum(1 for ts in type_sets_v if t in ts) >= 20]
    Zw = np.column_stack(
        [np.ones(nv)]
        + [np.array([t in ts for ts in type_sets_v], np.float64)
           for t in big_types]
        + [log_nv])
    Zwinv = np.linalg.pinv(Zw)
    wr = np.nan_to_num(when_rate, nan=float(np.nanmean(when_rate)))
    ew = wr - Zw @ (Zwinv @ wr)

    # pure-carrier indicators (choice c)
    fam_idx = {f: A.FAMILIES.index(f) for f in A.FAMILIES}
    pure = {}
    emit("## 3a. Co-carriage and pure carriers")
    emit()
    emit("| Family | Carriers | Pure (permissive) | Pure (strict) |")
    emit("|--------|----------|-------------------|----------------|")
    for fam in ("EXPRESS", "EVALUATE", "LABEL"):
        a = Lv[:, fam_idx[fam]] > 0
        others_fn = [f for f in FUNCTION_FAMS if f != fam]
        perm_pure = a & ~np.any(
            Lv[:, [fam_idx[f] for f in others_fn]] > 0, axis=1)
        allothers = [f for f in A.FAMILIES if f != fam]
        strict = a & ~np.any(
            Lv[:, [fam_idx[f] for f in allothers]] > 0, axis=1)
        pure[fam] = perm_pure.astype(np.float32)
        emit("| {} | {} | {} | {} |".format(fam, int(a.sum()),
                                            int(perm_pure.sum()),
                                            int(strict.sum())))
    emit()
    emit("Co-carriage matrix (formats carrying both; Jaccard in "
         "parentheses):")
    emit()
    emit("| | " + " | ".join(A.FAMILIES) + " |")
    emit("|--|" + "--|" * len(A.FAMILIES))
    for f1 in A.FAMILIES:
        cells = []
        a1 = Lv[:, fam_idx[f1]] > 0
        for f2 in A.FAMILIES:
            a2 = Lv[:, fam_idx[f2]] > 0
            inter = int((a1 & a2).sum())
            union = int((a1 | a2).sum())
            cells.append("{} ({:.2f})".format(
                inter, inter / union if union else 0.0)
                if f1 != f2 else str(int(a1.sum())))
        emit("| {} | {} |".format(f1, " | ".join(cells)))
    emit()
    run_pure = [f for f in ("EXPRESS", "EVALUATE", "LABEL")
                if pure[f].sum() >= config.PURE_CARRIER_MIN]
    skipped_pure = [f for f in ("EXPRESS", "EVALUATE", "LABEL")
                    if f not in run_pure]
    if skipped_pure:
        emit("Pure-carrier contrasts skipped (permissive carriers < {}): "
             "{}.".format(config.PURE_CARRIER_MIN, ", ".join(skipped_pure)))
        emit()

    # ------------------------------------------------------------------
    # the mega permutation loop
    def all_stats(Lc, pure_perm):
        out = {}
        M = (Lc @ Lc.T) > 0
        for lay in LAYERS:
            out[("omnibus", lay)] = A.headline_stat(S_dict[lay], M, nv)[0]
        for fam in ns.contrast_fams:
            a = Lc[:, fam_idx[fam]]
            for lay in LAYERS:
                mw, mb, _, _ = A.pair_means(S_dict[lay], a)
                out[(fam, lay)] = mw - mb
            ab = a > 0
            w = (ab[iu[0]] & ab[iu[1]]).astype(np.float64)
            if fam in ("EVALUATE", "LABEL"):
                ex = w - Z3 @ (Z3inv @ w)
                d = float(ex @ ex)
                out[(fam, "reg_fw")] = float(ex @ ey3["fw"]) / d
                out[(fam, "reg_pos")] = float(ex @ ey3["pos"]) / d
            if fam in CONT_REG:
                ex = w - Zc @ (Zcinv @ w)
                out[(fam, "reg_content")] = float(ex @ eyc) / float(ex @ ex)
            if fam in ANISO_FAMS:
                mw, mb, _, _ = A.pair_means(S_centred, a)
                out[(fam, "centred")] = mw - mb
            if fam in INST_FAMS:
                mw, mb, _, _ = A.pair_means(S_inst, a)
                out[(fam, "inst")] = mw - mb
        # when-clause Type-controlled coefficient
        cr = (Lc[:, fam_idx["RESPOND"]] > 0).astype(np.float64)
        exw = cr - Zw @ (Zwinv @ cr)
        d = float(exw @ exw)
        out[("RESPOND", "when_typectl")] = (float(exw @ ew) / d
                                            if d else np.nan)
        for fam in run_pure:
            mw, mb, _, _ = A.pair_means(
                S_dict[BINDING[fam]], pure_perm[fam])
            out[(fam, "pure")] = mw - mb
        return out

    obs = all_stats(Lv, pure)
    nulls = {k: np.empty(NP_, np.float32) for k in obs}
    rng = np.random.default_rng(config.RANDOM_SEED)
    for t in range(NP_):
        idx = rng.permutation(nv)
        st = all_stats(Lv[idx], {f: pure[f][idx] for f in run_pure})
        for k, v in st.items():
            nulls[k][t] = v
        if (t + 1) % 1000 == 0:
            print("  mega perms {}/{}".format(t + 1, NP_))

    # when-clause carrier contrast (bootstrap, as in 04/04F)
    jr = fam_idx["RESPOND"]
    a = (Lv[:, jr] > 0) & ~np.isnan(when_rate)
    b = (Lv[:, jr] == 0) & ~np.isnan(when_rate)
    va, vb = when_rate[a], when_rate[b]
    brng = np.random.default_rng(config.RANDOM_SEED)
    bd = [va[brng.integers(0, len(va), len(va))].mean()
          - vb[brng.integers(0, len(vb), len(vb))].mean()
          for _ in range(config.BOOTSTRAP_N)]
    wlo, whi = np.quantile(bd, [0.025, 0.975])
    when_unc = (float(va.mean() - vb.mean()), float(wlo), float(whi))

    # ------------------------------------------------------------------
    # capped reference values
    bc = pd.read_csv(config.OUTPUTS_DIR / "blockc_grid.csv")
    bb = pd.read_csv(config.OUTPUTS_DIR / "blockb_grid.csv")
    ba = pd.read_csv(config.OUTPUTS_DIR / "blocka_inference.csv")
    bf = pd.read_csv(config.OUTPUTS_DIR / "blockf_retest.csv")
    LKEY = {"fw": "fw_negjsd", "pos": "pos_cosine",
            "content": "content_cosine", "visual": "visual_cosine"}

    def capped_cell(key):
        kind, fam, lay = key
        if kind == "one_vs_rest":
            if fam == "(omnibus)":
                if lay in ("fw", "pos"):
                    r = ba[(ba["contrast"] == "headline") &
                           (ba["measure"] == LKEY[lay])].iloc[0]
                    return float(r["effect"]), float(r["p_twosided"])
                src = bb if lay == "content" else bc
                r = src[(src["family"] == "(omnibus)") &
                        (src["layer"] == LKEY[lay])].iloc[0]
                return float(r["effect"]), float(r["p_twosided"])
            r = bc[(bc["family"] == fam) & (bc["layer"] == LKEY[lay]) &
                   (bc["kind"] == "one_vs_rest")].iloc[0]
            return float(r["effect"]), float(r["p_twosided"])
        if kind == "reg_form":
            r = bc[(bc["family"] == fam) & (bc["layer"] == LKEY[lay]) &
                   (bc["kind"] == "mrqap_content_visual_controlled")].iloc[0]
            return float(r["effect"]), float(r["p_twosided"])
        if kind == "reg_content":
            r = bc[(bc["family"] == fam) &
                   (bc["kind"] == "mrqap_visual_controlled")].iloc[0]
            return float(r["effect"]), float(r["p_twosided"])
        return np.nan, np.nan

    emit("## 1b. Capped vs uncapped grid")
    emit()
    emit("| Cell | Capped effect (p2) | Uncapped effect | p_up | p_lo | p_2 "
         "| Capped cat | Uncapped cat | Agree |")
    emit("|------|--------------------|-----------------|------|------|-----|"
         "-----------|--------------|-------|")
    flips = []

    def grid_compare(key, obs_key, label):
        ce, cp2 = capped_cell(key)
        o = obs[obs_key]
        pu, pl, p2 = three_ps(o, nulls[obs_key])
        cc, uc = sig_cat(ce, cp2), sig_cat(o, p2)
        agree = cc == uc
        if not agree:
            flips.append(label)
        GRID_ROWS.append({
            "cell": label, "capped_effect": ce, "capped_p2": cp2,
            "uncapped_effect": round(float(o), 6),
            "p_upper": round(pu, 6), "p_lower": round(pl, 6),
            "p_twosided": round(p2, 6), "capped_cat": cc,
            "uncapped_cat": uc, "agree": agree})
        emit("| {} | {:+.5f} ({:.4f}) | {:+.5f} | {:.4f} | {:.4f} | {:.4f} "
             "| {} | {} | {} |".format(label, ce, cp2, o, pu, pl, p2,
                                       cc, uc, "yes" if agree else "FLIP"))

    for lay in LAYERS:
        grid_compare(("one_vs_rest", "(omnibus)", lay),
                     ("omnibus", lay), "omnibus_{}".format(lay))
    for fam in ns.contrast_fams:
        for lay in LAYERS:
            grid_compare(("one_vs_rest", fam, lay), (fam, lay),
                         "{}_{}".format(fam, lay))
    for fam, lay in FORM_REG:
        grid_compare(("reg_form", fam, lay),
                     (fam, "reg_" + lay), "reg_{}_{}".format(fam, lay))
    for fam in CONT_REG:
        grid_compare(("reg_content", fam, None),
                     (fam, "reg_content"), "reg_{}_content".format(fam))
    bfw = bf[bf["cell"] == "RESPOND_when_clause"].iloc[0]
    emit("| RESPOND when-clause | {:+.4f} (full data) | {:+.4f} "
         "[{:+.4f}, {:+.4f}] | - | - | - | sig+ | {} | {} |".format(
             float(bfw["full_effect"]), when_unc[0], when_unc[1], when_unc[2],
             "sig+" if when_unc[1] > 0 else "n.s.",
             "yes" if when_unc[1] > 0 else "FLIP"))
    if when_unc[1] <= 0:
        flips.append("RESPOND_when_clause")
    emit()
    if flips:
        emit("DECISION RULE (b): FLIPS found -> to chat before drafting: "
             "{}.".format(", ".join(flips)))
    else:
        emit("DECISION RULE (b): every cell agrees in sign and significance "
             "category. The paper reports the capped analysis as "
             "prespecified primary and this uncapped analysis as the "
             "scale/robustness analysis.")
    emit()

    # ------------------------------------------------------------------
    emit("## 2. Size-precision diagnostic")
    emit()
    srng = np.random.default_rng(config.RANDOM_SEED)
    vset = set(vidx.tolist())
    stab = []
    for r, poss in fmt_groups.items():
        if r not in vset:
            continue
        rposs = [p for p in poss if retained[p]]
        if len(rposs) < 10:
            continue
        perm = srng.permutation(len(rposs))
        h1 = [rposs[i] for i in perm[:len(rposs) // 2]]
        h2 = [rposs[i] for i in perm[len(rposs) // 2:]]

        def half_prof(ps):
            f = np.zeros(len(ns.STOP))
            tvec = defaultdict(float)
            for p in ps:
                for i, c in inst_fw[p].items():
                    f[i] += c
                for g, c in inst_tri[p].items():
                    tvec[g] += c
            return f, tvec

        f1, t1 = half_prof(h1)
        f2, t2 = half_prof(h2)
        if f1.sum() == 0 or f2.sum() == 0:
            continue
        rf = np.corrcoef(f1 / f1.sum(), f2 / f2.sum())[0, 1]
        keys = sorted(set(t1) | set(t2))
        v1 = np.array([t1.get(g, 0.0) for g in keys])
        v2 = np.array([t2.get(g, 0.0) for g in keys])
        rp = np.corrcoef(v1 / max(v1.sum(), 1), v2 / max(v2.sum(), 1))[0, 1]
        stab.append((len(rposs), rf, rp))
    stab = pd.DataFrame(stab, columns=["n", "r_fw", "r_pos"])
    stab["bin"] = pd.qcut(stab["n"], 10, labels=False, duplicates="drop")
    emit("Split-half profile stability vs instance count (deciles of n; "
         "{} formats with >= 10 retained instances):".format(len(stab)))
    emit()
    emit("| n decile | median n | mean r (FW) | mean r (POS) |")
    emit("|----------|----------|-------------|--------------|")
    for b, g in stab.groupby("bin"):
        emit("| {} | {:.0f} | {:.3f} | {:.3f} |".format(
            int(b) + 1, g["n"].median(), g["r_fw"].mean(), g["r_pos"].mean()))
        CHECK_ROWS.append({"check": "split_half", "key": "decile_{}".format(
            int(b) + 1), "value": round(float(g["r_fw"].mean()), 4),
            "value2": round(float(g["r_pos"].mean()), 4),
            "n": int(g["n"].median())})
    emit()
    min_n = np.minimum(log_nv[iu[0]], log_nv[iu[1]])
    bins = pd.qcut(min_n, 10, labels=False, duplicates="drop")
    emit("Pair similarity vs min(instance count) (deciles; uncapped):")
    emit()
    emit("| min-n decile | mean fw | mean pos | mean content |")
    emit("|--------------|---------|----------|--------------|")
    for b in range(int(bins.max()) + 1):
        m = bins == b
        emit("| {} | {:.4f} | {:.4f} | {:.4f} |".format(
            b + 1, y_form["fw"][m].mean(), y_form["pos"][m].mean(),
            content_v[m].mean()))
        CHECK_ROWS.append({"check": "pair_size_gradient",
                           "key": "decile_{}".format(b + 1),
                           "value": round(float(y_form["fw"][m].mean()), 5),
                           "value2": round(float(y_form["pos"][m].mean()), 5),
                           "n": int(m.sum())})
    emit()
    emit("Within-family coefficients with vs without log-size terms "
         "(uncapped, observed only - inference for these cells is in "
         "section 1b):")
    emit()
    emit("| Family | Measure | beta with size terms | beta without |")
    emit("|--------|---------|----------------------|--------------|")
    Zs = np.column_stack([np.ones(len(stype_v)),
                          stype_v.astype(np.float64), lsum_v])
    Zsi = np.linalg.pinv(Zs)
    Zn = np.column_stack([np.ones(len(stype_v)), stype_v.astype(np.float64)])
    Zni = np.linalg.pinv(Zn)
    for fam in ns.contrast_fams:
        ab = Lv[:, fam_idx[fam]] > 0
        w = (ab[iu[0]] & ab[iu[1]]).astype(np.float64)
        for meas in ("fw", "pos", "content"):
            y = y_form[meas] if meas in y_form else content_v
            bw = (lambda ex, eyv: float(ex @ eyv) / float(ex @ ex))(
                w - Zs @ (Zsi @ w), y - Zs @ (Zsi @ y))
            bn = (lambda ex, eyv: float(ex @ eyv) / float(ex @ ex))(
                w - Zn @ (Zni @ w), y - Zn @ (Zni @ y))
            emit("| {} | {} | {:+.5f} | {:+.5f} |".format(fam, meas, bw, bn))
            CHECK_ROWS.append({"check": "size_absorption",
                               "key": "{}_{}".format(fam, meas),
                               "value": round(bw, 6), "value2": round(bn, 6),
                               "n": ""})
    emit()

    # ------------------------------------------------------------------
    emit("## 3b. Pure-carrier contrasts (binding layers; permissive "
         "definition)")
    emit()
    emit("| Family | Layer | Standard effect | Pure effect | p_up | p_lo | p_2 |")
    emit("|--------|-------|-----------------|-------------|------|------|-----|")
    for fam in run_pure:
        lay = BINDING[fam]
        o = obs[(fam, "pure")]
        pu, pl, p2 = three_ps(o, nulls[(fam, "pure")])
        emit("| {} | {} | {:+.5f} | {:+.5f} | {:.4f} | {:.4f} | {:.4f} |".format(
            fam, lay, obs[(fam, lay)], o, pu, pl, p2))
        CHECK_ROWS.append({"check": "pure_carrier", "key": "{}_{}".format(
            fam, lay), "value": round(float(o), 6),
            "value2": round(p2, 6), "n": int(pure[fam].sum())})
    emit()

    emit("## 3c. When-clause Type control")
    emit()
    o = obs[("RESPOND", "when_typectl")]
    pu, pl, p2 = three_ps(o, nulls[("RESPOND", "when_typectl")])
    emit("- when_clause_rate ~ RESPOND_carrier + Type dummies ({} Types "
         ">= 20 formats) + log n: RESPOND coefficient = {:+.5f}; p_up "
         "{:.4f}, p_lo {:.4f}, p_2 {:.4f}.".format(
             len(big_types), o, pu, pl, p2))
    CHECK_ROWS.append({"check": "when_typectl", "key": "RESPOND",
                       "value": round(float(o), 6), "value2": round(p2, 6),
                       "n": nv})
    emit()

    emit("## 3d. Content-space anisotropy")
    emit()
    emit("| Family | Centroid effect (p2, section 1b) | Mean-centred effect "
         "| p_up | p_lo | p_2 |")
    emit("|--------|----------------------------------|---------------------"
         "|------|------|-----|")
    for fam in ANISO_FAMS:
        o = obs[(fam, "centred")]
        pu, pl, p2 = three_ps(o, nulls[(fam, "centred")])
        _, _, p2u = three_ps(obs[(fam, "content")], nulls[(fam, "content")])
        emit("| {} | {:+.5f} ({:.4f}) | {:+.5f} | {:.4f} | {:.4f} | {:.4f} |".format(
            fam, obs[(fam, "content")], p2u, o, pu, pl, p2))
        CHECK_ROWS.append({"check": "anisotropy", "key": fam,
                           "value": round(float(o), 6),
                           "value2": round(p2, 6), "n": nv})
    emit()
    emit("Instance-level content variant (mean cross-format instance-pair "
         "cosine, <= {} instances per format, seeded; measure check, not "
         "primary):".format(config.INSTANCE_CONTENT_SUBSAMPLE))
    emit()
    for fam in INST_FAMS:
        o = obs[(fam, "inst")]
        pu, pl, p2 = three_ps(o, nulls[(fam, "inst")])
        cen = obs[(fam, "content")]
        agree = "agrees" if (o > 0) == (cen > 0) and p2 < 0.05 else (
            "agrees (sign)" if (o > 0) == (cen > 0) else "DISAGREES")
        emit("- {}: instance-level effect {:+.5f} (p_2 {:.4f}) vs centroid "
             "{:+.5f} -> {}.".format(fam, o, p2, cen, agree))
        CHECK_ROWS.append({"check": "instance_content", "key": fam,
                           "value": round(float(o), 6),
                           "value2": round(p2, 6), "n": ""})
    emit()
    emit("This is the final analysis block before drafting unless a flip or "
         "a section-3 surprise sends something back to chat.")

    # figure: capped vs uncapped scatter
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    g = pd.DataFrame(GRID_ROWS)
    fig, ax = plt.subplots(figsize=(5.5, 5.5))
    ax.scatter(g["capped_effect"], g["uncapped_effect"], s=18, alpha=0.8,
               c=np.where(g["agree"], "tab:blue", "tab:red"))
    lim = max(abs(g["capped_effect"]).max(), abs(g["uncapped_effect"]).max()) * 1.1
    ax.plot([-lim, lim], [-lim, lim], color="grey", lw=0.6)
    ax.axhline(0, color="black", lw=0.4)
    ax.axvline(0, color="black", lw=0.4)
    ax.set_xlabel("capped effect (committed primary)")
    ax.set_ylabel("uncapped, denoised effect")
    ax.set_title("Capped vs uncapped grid ({} cells; red = category flip)".format(len(g)))
    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(figs / ("blockg_scatter." + ext), dpi=200)
    plt.close(fig)
    emit()
    emit("Figure: blockg_scatter (PDF+PNG).")

    pd.DataFrame(GRID_ROWS).to_csv(config.OUTPUTS_DIR / "blockg_grid.csv",
                                   index=False, encoding="utf-8")
    pd.DataFrame(CHECK_ROWS).to_csv(config.OUTPUTS_DIR / "blockg_checks.csv",
                                    index=False, encoding="utf-8")
    emit("Wrote outputs/blockg_grid.csv ({} rows) and "
         "outputs/blockg_checks.csv ({} rows).".format(
             len(GRID_ROWS), len(CHECK_ROWS)))
    (config.OUTPUTS_DIR / "blockg_report.md").write_text(
        "\n".join(REPORT_LINES), encoding="utf-8")
    print("Report written to outputs/blockg_report.md")


if __name__ == "__main__":
    main()
