"""05_audit_stats.py - audit statistics per 04_ANALYSIS_SPEC.md section 8.

Run: python scripts/05_audit_stats.py
Runnable independently whenever the filled audit files land. Report-only;
no hard gate. Writes outputs/audit_stats.md when at least one audit file
is filled; otherwise says which files are still blank and exits.

Expected files (outputs/samples/):
- audit_clauses_150.csv  (A1: is_genuine_gloss, label_correct)
- audit_label_25.csv     (A1, LABEL top-up; reported separately)
- audit_nogloss_100.csv  (A1: missed_gloss)
- audit_clauses_50_A2.csv (A2 copy of rows 1-50; kappa on the overlap)
"""
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import config

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

LINES = []


def emit(line=""):
    print(line)
    LINES.append(line)


def norm_yn(series):
    return series.fillna("").astype(str).str.strip().str.upper()


def filled(series):
    return norm_yn(series).isin(("Y", "N"))


def cohen_kappa(a, b):
    """Cohen's kappa for two aligned Y/N series."""
    n = len(a)
    if n == 0:
        return float("nan")
    po = (a == b).mean()
    pe = sum(((a == c).mean()) * ((b == c).mean()) for c in ("Y", "N"))
    if pe == 1.0:
        return float("nan")
    return (po - pe) / (1.0 - pe)


def main():
    s = config.SAMPLES_DIR
    emit("# Audit statistics (04 spec section 8)")
    emit()
    emit("Generated by scripts/05_audit_stats.py on {}.".format(
        datetime.now().strftime("%Y-%m-%d %H:%M")))
    emit()

    any_filled = False

    # Precision, A1 main sample
    a1 = pd.read_csv(s / "audit_clauses_150.csv", dtype=str)
    f = filled(a1["is_genuine_gloss"])
    if f.any():
        any_filled = True
        g = norm_yn(a1.loc[f, "is_genuine_gloss"]) == "Y"
        emit("## Precision (A1, main sample)")
        emit()
        emit("- Judged rows: {} of {}".format(f.sum(), len(a1)))
        emit("- Precision (is_genuine_gloss = Y): {}/{} = {:.3f}".format(
            g.sum(), f.sum(), g.mean()))
        lc = a1.loc[f & (norm_yn(a1["is_genuine_gloss"]) == "Y")]
        lcf = filled(lc["label_correct"])
        if lcf.any():
            ok = norm_yn(lc.loc[lcf, "label_correct"]) == "Y"
            emit("- Label accuracy among genuine glosses: {}/{} = {:.3f}".format(
                ok.sum(), lcf.sum(), ok.mean()))
        emit()
    else:
        emit("- audit_clauses_150.csv: not yet filled.")

    # Precision, LABEL top-up (reported separately)
    p = s / "audit_label_25.csv"
    if p.exists():
        lt = pd.read_csv(p, dtype=str)
        f = filled(lt["is_genuine_gloss"])
        if f.any():
            any_filled = True
            g = norm_yn(lt.loc[f, "is_genuine_gloss"]) == "Y"
            emit("## Precision (A1, LABEL top-up; separate, not pooled)")
            emit()
            emit("- Judged rows: {} of {}".format(f.sum(), len(lt)))
            emit("- Precision: {}/{} = {:.3f}".format(g.sum(), f.sum(), g.mean()))
            emit()
        else:
            emit("- audit_label_25.csv: not yet filled.")
    else:
        emit("- audit_label_25.csv: absent.")

    # Recall proxy
    ng = pd.read_csv(s / "audit_nogloss_100.csv", dtype=str)
    f = filled(ng["missed_gloss"])
    if f.any():
        any_filled = True
        miss = norm_yn(ng.loc[f, "missed_gloss"]) == "Y"
        emit("## Recall proxy (A1, no-gloss sample)")
        emit()
        emit("- Judged rows: {} of {}".format(f.sum(), len(ng)))
        emit("- missed_gloss = Y: {}/{} = {:.3f} (higher = more glosses "
             "missed by the extractor)".format(miss.sum(), f.sum(), miss.mean()))
        emit()
    else:
        emit("- audit_nogloss_100.csv: not yet filled.")

    # Kappa on the 50-row overlap
    p2 = s / "audit_clauses_50_A2.csv"
    if p2.exists():
        a2 = pd.read_csv(p2, dtype=str)
        merged = a1.merge(a2, on=["entry_id", "clause_text"],
                          suffixes=("_a1", "_a2"))
        f = (filled(merged["is_genuine_gloss_a1"]) &
             filled(merged["is_genuine_gloss_a2"]))
        if f.any():
            any_filled = True
            ya1 = norm_yn(merged.loc[f, "is_genuine_gloss_a1"])
            ya2 = norm_yn(merged.loc[f, "is_genuine_gloss_a2"])
            emit("## Agreement (50-row overlap)")
            emit()
            emit("- Aligned, doubly-judged rows: {}".format(f.sum()))
            emit("- Raw agreement on is_genuine_gloss: {:.3f}".format(
                (ya1 == ya2).mean()))
            emit("- Cohen's kappa: {:.3f}".format(cohen_kappa(ya1.values, ya2.values)))
            emit()
        else:
            emit("- audit_clauses_50_A2.csv: present but not doubly judged yet.")
    else:
        emit("- audit_clauses_50_A2.csv: absent.")

    emit()
    emit("Report-only; no hard gate. Discussion happens in chat.")

    if any_filled:
        out = config.OUTPUTS_DIR / "audit_stats.md"
        out.write_text("\n".join(LINES), encoding="utf-8")
        print("Written to {}".format(out))
    else:
        print("No filled audit files yet; nothing written.")


if __name__ == "__main__":
    main()
